sourcenetwork/defradb

events/events.go, events/simple.go
Resolves #1351 #1349
May also resolve much of the current test flakiness, but there may be other underlying issues so I'll leave those open for a bit. It does not resolve all of the flakiness and I have seen one P2P local failure on this branch (logged in https://github.com/sourcenetwork/defradb/issues/1338 )
Modifies the simpleChannel to guarantee the processing order of stuff. 
The previous solution did not do this, and allowed new subscriptions to pick up database events that had previously occurred but had not yet been processed by `handleChannel`.
A common scenario for how this can result in a test failure is documented in #1351
Also includes a fix for https://github.com/sourcenetwork/defradb/issues/1349 as I believe it occurs in the same part of the codebase, for similar reasons, …
=> fix: Guarantee event processing order

.github/workflows/build-ami-with-packer.yml, tools/cloud/aws/packer/build_aws_ami.pkr.hcl
Resolves #1343
Fixes the issue by bumping Golang dependency it will build to `v1.19.8`.
Manually on `v0.5.0`, here is the passing action: https://github.com/sourcenetwork/defradb/actions/runs/4684981654/jobs/8301658218
- WSL2 (Manjaro)
=> ci: Bump go version within packer for AWS AMI

net/peer.go
Resolves #1367
Unlocks a lock that is held before returning an error.
Unlikely to be tripping up any of our tests, but is undesirable and should be fixed.
=> fix: Unlock replicator lock before returning error

.github/workflows/code-test-coverage.yml, .github/workflows/run-tests.yml
Resolves #1391
Removes code cov token from the code cov workflow, and changes the tests workflows to run on pull request.
=> ci: Allow CI to work from forked repo

db/txn_db.go, tests/integration/mutation/simple/create/simple_test.go
Resolves #1382
Does not commit if errors have been returned.  This allowed changes to be persisted on error.
Note: First commit documents the error, second commit fixes it.
=> fix: Do not commit if errors have been returned

request/graphql/schema/descriptions.go, request/graphql/schema/generate.go, request/graphql/schema/manager.go, request/graphql/schema/types/base.go, request/graphql/schema/types/commits.go, request/graphql/schema/types/descriptions.go, request/graphql/schema/types/types.go, tests/integration/mutation/simple/delete/multi_ids_test.go, tests/integration/mutation/simple/update/with_filter_test.go, tests/integration/query/simple/with_group_test.go, tests/integration/query/simple/with_limit_offset_test.go, tests/integration/query/simple/with_order_test.go
Resolves #796
Adds descriptions to all system defined GQL stuff (fields, args, enum values, etc). Also adds a couple of missing tests that I needed in order to be sure of the behaviour I was documenting.
I'm not terribly fussed about the location of the constant declarations, this will need to be redone once Pavneet and co have decided on how they wish to manage these long-term.
All the descriptions have been added in the last commit only, other commits include misc changes (such as tests).
Tested via Altair:
=> feat: Add descriptions to all system defined GQL stuff

api/http/handlerfuncs.go, api/http/handlerfuncs_test.go, api/http/request_result.go
Resolves #1383 
Serializes DB errors to json in http package. They were previously resolving to `"{}"`.
=> fix: Serialize DB errors to json in http package

client/dockey.go, go.mod, go.sum
Resolves #1221 
This PR changes `github.com/satori/go.uuid` for `github.com/gofrs/uuid/v5`.
make test
- MacOS
=> chore: Move to gofrs/uuid

net/peer.go, net/server.go, tests/integration/p2p.go
Resolves #1334
Resolves #1335 
Resolves #1336
Resolves #1337
Resolves #1338
Resolves #1375
This PR seems to have fixed all known flakyness from the P2P integration tests. It does so at different levels:
1. We prevent pre peer connection and pre replicator configuration actions from having their events received by the wait function by adding a 100ms sleep call pre setup.
2. We ensure that the wait go routines are ready before continuing with the actions.
3. We add a docQueue to the PushLog function so that we don't handle multiple updates to the same document at once. This helps avoid unnecessary transaction conflicts. This would also sometimes cause the PushLog function to hang and the RPC call hitting a timeout.
4. We handle pubsub topic subscriptions a little better by subscribing only …
=> fix: Improve P2P event handling

README.md
Resolves #1353
- Add go report card badge
- Add code coverage badge
- Add test action status badge
- Add twitter badge
- Add discord badge
Can check how it looks here: https://github.com/sourcenetwork/defradb/tree/lone/docs/badges
=> docs: Add codcov and go report card badges

api/http/handlerfuncs.go
Resolves #1322
Limits the size of http request bodies that we handle to make things slightly harder for anyone to DoS a defra node.
Timeout time preferred by me over a byte limit as I find it much more descriptive, and will scale nicely with the system/hardware-context (more powerful machines can handle bigger req. bodies). Is undoubtably a runtime cost involved though compared to just using an int.
I set all the limits to 1 second, as that seems like plenty for now.  Should be added to the config at somepoint IMO though (not now).
=> fix: Limit the size of http request bodies that we handle

README.md, cli/start.go, config/config.go, config/configfile_yaml.gotmpl
Resolves #1355 
This PR adds the option to set allowed origins for the HTTP API using the config file or a CLI flag.
Unit tests and curl with allowedOrigins set to http://test.com
```shell
curl -i http://localhost:9181/api/v1/ping -H "Origin: http://no.com" -H "Access-Control-Request-Method: GET" -X OPTIONS
curl -i http://localhost:9181/api/v1/ping -H "Origin: http://test.com" -H "Access-Control-Request-Method: GET" -X OPTIONS
```
- MacOS
=> feat: Add allowed origins config

README.md, api/http/errors.go, api/http/handlerfuncs_test.go, api/http/server.go, cli/peerid.go, cli/peerid_test.go, cli/replicator_delete.go, cli/replicator_set.go, client/dockey.go, db/collection.go, net/client.go, net/pb/net.proto, net/peer.go, net/server.go, node/node.go, tests/integration/cli/client_peerid_test.go
Tackles #1430 (but doesn't fully resolve it)
- fix one SchemaID value logging the function instead of the resulting of calling the function
- more consistency. prefer PeerID over PID
CI
=> chore: Improve logging consistency

.github/workflows/lint.yml
Resolves #1435
Add a Lint only workflow.
CI on branch of a fork and this PR
=> ci: Add a separate workflow to run the linter

.github/workflows/build-ami-with-packer.yml, tools/cloud/aws/packer/build_aws_ami.pkr.hcl
Resolves #1425
- Shreds the keys in all locations noted in the issue.
- Generated the AMI of name: `source-defradb-v0.5.0-20230501085514` , with ID: `ami-0814ed8a30589825b`
- Manually tested the commands after sshing into the image, to ensure the work, and manually generated a run.
- The run that generated the AMI successfully can be found here: https://github.com/sourcenetwork/defradb/actions/runs/4849906529/jobs/8642330562?pr=1426
=> ci: Fix the SSH security issue from AMI scan report

docs/data_format_changes/i1186-change-detctor-setup.md, tests/integration/change_detector.go, tests/integration/explain/utils.go, tests/integration/utils2.go
Resolves #1186
Partially resolves #1342
Improves the change detector performance. Decreases runtime from 17 minutes to 5 minutes on my local machine. It also cleans up the paths used by the change detector (part of https://github.com/sourcenetwork/defradb/issues/1342).
It does this by changing how the setup-stage is handled, instead of calling `go test` once per test, it now only calls it once per test package - setting up a bunch of test db instances for the entire package.
This does mean that they can no longer rely on the use of `test.TempDir`, and instead the database instances live within the temp directory. This PR does not provide a mechanic to clean those up, but it should be quite easy to do so later.  The total disk usage by a full test run is on 44MB (post run, during a run it …
=> test: Improve change detector performance

.github/workflows/detect-change.yml, tests/integration/utils2.go
Resolves #1437
Removes secret ssh key stuff from change detector workflow.
=> ci: Remove secret ssh key stuff from change detector wf

README.md
Resolves #1439
This PR fixes the link to the query language documentation in the Readme file as well as removing an inaccurate CLI command for setting a replicator.
N/A
=> fix: Update QL documentation link and replicator command

go.mod, go.sum, request/graphql/schema/generate.go
Resolves #
This PR updates to the latest version of graphql-go. The update changed the formatting of `object.Name()` which caused issued with our gql parsing and filtering.
Thanks to @AndrewSisley for sorting our the gql issues.
make test
(*replace*) Describe the tests performed to verify the changes. Provide instructions to reproduce them.
- MacOS
=> chore: Update graphql-go

tests/integration/net/state/simple/replicator/with_create_test.go
Resolves #863
Adds tests to assert schema id order independence.  Ticket suggested the go json lib is order dependent, this appears to be untrue.
=> test: Add tests to assert schema id order independence

cli/start.go
Resolves #1458
Simply adds SIGTERM to the list of handled signals.
I'm unsure how to test this. We can send send a signal, `syscall.Kill(syscall.Getpid(), syscall.SIGINT)` within an integration test but I'm worried it will end the test process which also is running the other tests.
It might require an 'external' integration test suite in which we can run the command and then send the signal to the process.
Manually
=> fix: Handling SIGTERM in CLI `start` command

README.md
Resolves #1465
Reference collectionID instead of schemaVersionID in p2p readme. I think this wording might predate the introduction of the collectionID field.
=> fix: Reference collectionID in p2p readme

client/request/commit.go, client/request/consts.go, planner/commit.go, planner/mapper/commitSelect.go, planner/mapper/mapper.go, request/graphql/parser/commit.go, request/graphql/schema/types/commits.go, request/graphql/schema/types/descriptions.go, tests/integration/explain/default/dagscan_test.go, tests/integration/query/commits/with_dockey_field_test.go, tests/integration/query/commits/with_field_test.go, tests/integration/query/latest_commits/with_dockey_field_test.go, tests/integration/query/latest_commits/with_field_test.go, tests/integration/schema/updates/add/field/create_update_test.go, tests/integration/schema/updates/move/simple_test.go
Resolves #1452 
Renames commit `field` input arg to `fieldId`, to match the field `fieldId`. Includes the explain output.
=> fix: Rename commit field input arg to fieldId

cli/root.go, tests/integration/utils2.go
Resolves #-
Just some 'dead code' being remove. Feel free to add commits to this PR to remove further dead code.
`make`
=> chore: Remove some dead code

net/peer.go
Resolves #1389 
This PR improves the rollback of P2P collection manipulation errors. It ensures that a rollback is applied if the transaction commit fails.
Unit test coming with `net` package code coverage improvements.
=> refactor: Improve rollback on peer P2P collection error

tests/integration/explain/default/dagscan_test.go, tests/integration/explain/default/invalid_type_arg_test.go, tests/integration/explain/default/with_limit_count_test.go, tests/integration/explain/default/with_limit_join_test.go
- Part of #953
- Resolves #1473
Continue converting explain tests to the new explain setup before we can integrate the entire setup to the new action based setup. #953 Has a lot more detail on the entire plan.
- Fixes test names and some fixtures for the limit test.
- This PR converts all the default dagscan explain tests to the new explain setup.
- Converts a wrong usage explain test case.
=> test: Convert explain dagscan tests to new explain setup

tests/integration/explain/default/type_join_many_test.go, tests/integration/explain/default/type_join_one_test.go, tests/integration/explain/default/type_join_test.go, tests/integration/explain/default/with_limit_join_test.go
- Part of #953
- Resolves #1475
Continue converting explain tests to the new explain setup before we can integrate the entire setup to the new action based testing setup. #953 Has a lot more detail on the entire plan.
- Splits type join one tests into a separate file.
- Added some type join many tests into a separate file.
- This PR converts all the default typeJoin explain tests to the new explain setup.
- Keeps the mixed test that use both type of joins in the original file.
=> test: Convert explain join tests to new explain setup

tests/integration/explain/default/with_order_join_test.go, tests/integration/explain/default/with_order_test.go
- Part of #953
- Resolves #1477
Continue converting explain tests to the new explain setup before we can integrate the entire setup to the new action based setup. #953 Has a lot more detail on the entire plan.
- This PR converts all the default order explain tests to the new explain setup.
- Splits the order join tests into a separate file.
=> test: Convert explain order tests to new explain setup

tests/integration/explain/default/top_with_average_test.go, tests/integration/explain/default/top_with_count_test.go, tests/integration/explain/default/top_with_sum_test.go
- Part of #953
- Resolves #1479
Continue converting explain tests to the new explain setup before we can integrate the entire setup to the new action-based setup. #953 Has a lot more detail on the entire plan.
- This PR converts all the default top-level explain tests.
=> test: Convert explain top-level tests to new explain setup

net/peer.go
Resolves #1481 
Currently, we de not reconnect to known peers on restart unless the peer is defined in the config file or on the CLI command. This PR makes sure that we try to reconnect to known peers.
make test shows now degradation and tested manually that peers reconnect on restart.
- MacOS
=> fix: Add reconnection to known peers

tests/integration/explain/default/with_average_join_test.go, tests/integration/explain/default/with_average_test.go
- Part of #953
- Resolves #1484
Continue converting explain tests to the new explain setup before we can integrate the entire setup to the new action-based setup. #953 Has a lot more detail on the entire plan.
- This PR converts all the default explain average tests.
- Separates the average join tests into a new file.
=> test: Convert explain average tests to new explain setup

tests/integration/explain/default/with_sum_join_test.go, tests/integration/explain/default/with_sum_test.go
- Part of #953
- Resolves #1485
Continue converting explain tests to the new explain setup before we can integrate the entire setup to the new action-based setup. #953 Has a lot more detail on the entire plan.
- This PR converts all the default explain sum tests.
- Splits sum join tests in a separate PR.
=> test: Convert explain sum tests to new explain setup

tests/integration/explain/default/with_average_join_test.go, tests/integration/explain/default/with_count_join_test.go, tests/integration/explain/default/with_count_test.go
- Part of #953
- Resolves #1486 
Continue converting explain tests to the new explain setup before we can integrate the entire setup to the new action-based setup. #953 Has a lot more detail on the entire plan.
- This PR converts all the default explain count tests.
- Splits count join tests in a separate file.
- Adds some new tests that were missed before.
=> test: Convert explain count tests to new explain setup

tests/integration/change_detector.go
Resolves #1494
Skips new test packages in change detector instead of panicing when trying to run the setup tests.
Tested locally, ~~PR includes TEMP test commit that will be removed once it has allowed testing via the CI (PR will leave draft state at that point)~~ and with temp CI test to trigger bug.
=> fix: Skip new test packages in change detector

connor/eq.go, go.mod, go.sum, tests/integration/explain/default/delete_test.go, tests/integration/explain/default/group_with_dockey_test.go, tests/integration/explain/default/group_with_filter_test.go, tests/integration/explain/default/top_with_average_test.go, tests/integration/explain/default/top_with_count_test.go, tests/integration/explain/default/top_with_sum_test.go, tests/integration/explain/default/with_average_join_test.go, tests/integration/explain/default/with_filter_test.go
Resolves #938 
Updates the graphql-go lib to [this](https://github.com/sourcenetwork/graphql-go/commit/fe7085512c230f9daec4afa8231bd10b9225852b) update, which applies proper scalar Int parsing and coercing to return `int32` instead of `int`.
This has *minor* downstream changes as you can see in this PR. Also had to update the explain tests @shahzadlone since it was using the filter types directly in the explain output which has now changed to `int32`
Manually + CI
- Ubuntu (WSL2)
=> refactor: Use `int32` for proper gql scalar Int parsing

api/http/handler_test.go, api/http/http.go, api/http/logger_test.go, cli/cli.go, cmd/genclidocs/genclidocs.go, cmd/genmanpages/main.go, config/config.go, datastore/store.go, db/db.go, logging/logging.go, merkle/clock/clock.go, merkle/crdt/merklecrdt.go, net/api/service.go, net/net.go, node/node.go, planner/planner.go, tests/bench/bench_util.go, tests/bench/query/simple/utils.go, tests/integration/cli/version_test.go, tests/integration/explain/utils.go, tests/integration/net/order/utils.go, tests/integration/utils2.go
Resolves #1148
Simple approach: just rename the loggers.
Suggestion: non-defra loggers could have a prefix like e.g. `x.` 
CI
=> chore: Enshrine defra logger names

net/peer.go, node/node.go, tests/bench/bench_util.go, tests/integration/change_detector.go, tests/integration/explain/utils.go, tests/integration/net/order/utils.go, tests/integration/net/state/simple/peer/with_update_restart_test.go, tests/integration/net/state/simple/peer_replicator/with_update_restart_test.go, tests/integration/net/state/simple/replicator/with_create_restart_test.go, tests/integration/p2p.go, tests/integration/query/simple/with_restart_test.go, tests/integration/test_case.go, tests/integration/utils2.go
Resolves #1082 
Adds DB/Node Restart tests.  This will be required by Lens (e.g. to make sure migrations are not lost on restart). IIRC I think this also found https://github.com/sourcenetwork/defradb/pull/1482 (also fixed by Fred).
Fred was a massive help here and fixed the difficult bits when I flaked out on Friday :) Any commit that lists him as an author are his, I am only tagged in them having rebased them.
Commits are messy as anything as I wanted to preserve the level of credit due to Fred, and I'd suggest reviewing this PR at PR level as cleanup has not been squashed into commits introducing broken/messy code.
I will merge this when approved, whether that is 0.5.1 or 0.6 - it introduces no breaking (or risky) changes to the production code.
=> test: Add DB/Node Restart tests

cli/request.go, examples/request/user_creation.graphql, examples/request/user_query.graphql, tests/integration/cli/client_query_test.go
Resolves #1258 
Adds support to read from a file to the `client query` CLI command, via `-f` flag, and a simple test for it, and two related examples in the `/examples` directory.
=> feat: CLI client request from file

tests/integration/utils2.go
Resolves #1207
Requires no errors when none expected instead of just asserting.  Asserts here typically result in panics which confuses the logs and the developer looking at them.
=> test: Require no errors when none expected

tests/integration/p2p.go, tests/integration/utils2.go
Resolves #1506
Previously the full wait-cycle would be calculated, meaning that if a Wait action was before the Restart action the Second wait action would progress once the expected number of events for the first Wait was received.  This changes it so that upon restart the wait calculation is started from just after the last wait action before the restart.
Had a few hundred successful runs of the only affect test i(`TestP2PPeerReplicatorWithUpdateAndRestart`) n the CI.
=> test: Resume wait correctly following test node restart

tests/integration/query/one_to_many/with_id_field_test.go, tests/integration/query/one_to_one/with_id_field_test.go
Resolves #1468 
Adds tests for foo_id field name clashes with relational id fields.
Fixing the issues is out of scope.
=> test: Add tests for foo_id field name clashes

planner/average.go, planner/commit.go, planner/count.go, planner/create.go, planner/delete.go, planner/group.go, planner/limit.go, planner/mapper/aggregate.go, planner/mapper/mapper.go, planner/mapper/select.go, planner/order.go, planner/scan.go, planner/select.go, planner/sum.go, planner/top.go, planner/update.go, tests/integration/query/one_to_many_to_one/with_filter_test.go, tests/integration/utils2.go
Resolves #1526 
This PR converts `core.DocumentMapping` in `mapper.Select` and `mapper.Aggregate` to a pointer. It also adds an integration test for the two level deep filter.
It also includes a fix of the change detector for when there are no other actions after SchemaUpdate, CreateDoc and UpdateDoc.
*Note: The pointer fix was found by @jsimnz.*
make test
- MacOS
=> fix: Change `core.DocumentMapping` to pointer

docs/data_format_changes/i1530-change-detector-without-non-mutations.md, tests/integration/utils2.go
Resolves #1530 
This PR fixes the previous fix and adds a breaking change document to prevent the broken cycle in the change detector after the fix. Should have been part of the #1528 although the change detector was passing before merge.
make test:changes
- MacOS
=> fix: Document change detector breaking change

tests/integration/explain/default/group_test.go, tests/integration/explain/default/group_with_average_test.go, tests/integration/explain/default/group_with_dockey_child_test.go, tests/integration/explain/default/group_with_dockey_test.go, tests/integration/explain/default/group_with_filter_child_test.go, tests/integration/explain/default/group_with_filter_test.go, tests/integration/explain/default/group_with_limit_child_test.go, tests/integration/explain/default/group_with_limit_test.go, tests/integration/explain/default/group_with_order_child_test.go, tests/integration/explain/default/group_with_order_test.go, tests/integration/explain/default/utils.go
- Part of #953
- Resolves #1536 
This PR is the last PR for default explain test conversions, this PR converts the remaining group tests.
- This PR converts all the default explain group tests.
- Separates some tests into their group child select cases.
- Added a few tests where there was a test gap.
Note: One more PR after this to convert the simple tests and then the integration to the new testing framework with the new explain testing setup can be done.
=> test: Convert explain group tests to new explain setup

tools/scripts/scripts_test.sh, tools/scripts/validate-conventional-style.sh
Resolves #1176
- Any previous valid label can now also support an additional decorator like so: `(i)` that will help signal that this commit/pr-title can be ignored from change-log.
Unit tests and CI
=> ci(i): Respect ignore decorator on PR title validation

.github/codecov.yml, .github/workflows/code-test-coverage.yml, Makefile
Resolves #1548
- Clean up config file and use the newer style.
- Try out patch and github annotations (seems like they fixed the bugs).
=> ci(i): Cleanup codecov config & enable annotations

docs/data_format_changes/i1602-no-change-tests-updated.md, tests/integration/mutation/relation/create/with_txn_test.go, tests/integration/mutation/relation/delete/with_txn_test.go, tests/integration/mutation/simple/delete/multi_ids_test.go, tests/integration/mutation/simple/delete/single_id_test.go, tests/integration/mutation/simple/mix/with_txn_test.go, tests/integration/test_case.go, tests/integration/utils.go, tests/integration/utils2.go
Resolves #1602
Instead of a dedicated txn action (like we currently have), we can instead follow a similar pattern to node ids where any action can specify a transaction id. I would like to use this on other actions, most immediately for Lens testing, although it will likely be very useful elsewhere too.
=> test: Rework transaction test framework capabilities

logging/logger.go
Resolves #1607
This PR wraps the pipe WriteSyncer with a Lock so that is can be used concurrently.
make test
- MacOS
=> fix: Change the WriteSyncer to use lock when piping

planner/mapper/mapper.go
Resolves #1615
Makes sure the requestable fields aren't duplicated 
Intergration tests
- MacOS
=> fix: Avoid duplicated requestable fields

connor/connor.go, connor/not.go, connor/not_test.go, planner/mapper/mapper.go, planner/mapper/targetable.go, tests/integration/query/simple/with_filter/with_not_test.go
Resolves #1542 
This PR add the `_not` operator as an option for filters in graphql queries.
make test
- MacOS
=> feat: Add `_not` operator

Makefile, client/document.go, client/document_test.go, client/errors.go, client/request/errors.go, client/request/select.go, core/cid/cid.go, datastore/blockstore_test.go, db/collection.go, db/collection_update.go, db/errors.go, merkle/clock/clock_test.go, merkle/clock/heads_test.go, planner/create.go, tests/integration/collection/create/one_to_many/simple_test.go, tests/integration/mutation/one_to_many/create/with_alias_test.go, tests/integration/mutation/one_to_many/create/with_simple_test.go, tests/integration/mutation/one_to_many/delete/with_show_deleted_test.go, tests/integration/mutation/one_to_many/update/related_object_link_test.go, tests/integration/mutation/one_to_many/update/related_object_link_with_alias_test.go, tests/integration/mutation/one_to_many/utils.go, tests/integration/mutation/one_to_one/create/with_alias_test.go, tests/integration/mutation/one_to_one/create/with_simple_test.go, tests/integration/mutation/one_to_one/update/related_object_link_test.go, tests/integration/mutation/one_to_one/update/related_object_link_with_alias_test.go, tests/integration/query/one_to_many/with_filter_related_id_test.go
Resolves #1279 
Here are the main tasks that were done in this PR:
In addition, I had to resolve a circular dependency but making the `core/cid.go` stuff it's own modular package. Refactored manual uses of `cid.Prefix` and dockey generation so that it's consistent.
- This commit `PR(FIX): Squash the dockey verification + diff bug` undoes some work in the commit `PR(CORE): Implement the alias logic for create` to fix a bug. Other than that should be "cleanish" history.
- Integration tests.
=> feat: Allow relation alias on create and update

db/collection_get.go, db/collection_index.go, db/fetcher/fetcher.go, db/fetcher/mocks/Fetcher.go, db/fetcher/mocks/utils.go, db/fetcher/versioned.go, db/fetcher_test.go, db/indexed_docs_test.go, lens/fetcher.go, planner/scan.go
Resolves #1623
Removes the redundant txn param from fetcher start as it is always the same value as fetcher.Init
=> refactor: Remove redundant txn param from fetcher start

tests/integration/explain.go, tests/integration/lens.go, tests/integration/p2p.go, tests/integration/state.go, tests/integration/test_case.go, tests/integration/utils2.go
Resolves #1644
Bundles all test state into single var.  Stuff was starting to get too messy as the action system expanded.  This makes all the stuff consistent, in name and location and removes the need to pass the individual items around as and when needed. All props have been documented.
It also simplifies refreshing state, as return values are no longer needed.  It opens the way to making the action system interface-based, which we can look at in the future if we want but not here in this PR.
=> test: Bundle test state into single var

Makefile
Resolves #1642
Removes CLI tests from `make test` as they take ages to run and it is disruptive to dev-flow.
Also adds `make test:short` which is even leaner, skipping all the extras like the race detector.
Runtimes on my machine:
Old `make test`: 72s
New `make test`: 30s
New `make test:short`: 21s
=> test: Remove CLI tests from make test

api/http/handlerfuncs.go, api/http/router.go, cli/cli.go, cli/schema_migration.go, cli/schema_migration_get.go, cli/schema_migration_set.go
Resolves #1648
Adds `schema migration set` and `schema migration get` commands to the CLI, and the http API.
Command/endpoint assumes the db server has access to the file path(s) provided in the lens cfg - it will error early if it doesn't (tested manually).
I've done some manual testing of this and it looks all good.  I'm happy merging this ASAP as time is now very short. Tests can be added later, possibly within this PR if I have time but do not count on it (https://github.com/sourcenetwork/defradb/issues/1652).
=> feat: Add schema migration get and set cmds to CLI

tests/integration/query/one_to_one/with_group_related_id_test.go
Because of #1672 
Disables test `TestQueryOneToOneWithGroupRelatedIDFromSecondary` so other PRs can be merged before the release.
=> test: Disable test

net/node.go
Resolves #1260 
This PR changes the peerstore prefix from `/peers/peers` to `/db/peers`
manual `defradb client dump`
- MacOS
=> fix: Remove duplicated `peers` in peerstore prefix

Makefile, cli/errors.go, cli/schema_migration_get.go, cli/schema_migration_set.go, cli/schema_patch.go, tests/integration/cli/client_schema_migration_get_test.go, tests/integration/cli/client_schema_migration_set_test.go
Resolves #1652
Standardises `schema migration set` errors. And errors if given unknown lens cfg properties.
Adds integration tests for the command.
=> fix: Standardise `schema migration` CLI errors

db/fetcher/encoded_doc.go, db/fetcher/fetcher.go, planner/scan.go, tests/integration/query/one_to_one/with_group_related_id_test.go
Resolves #1672
Fixes invalid datastore state where somehow the iterator is not closed properly, even though Close is called.  I am guessing that something is getting GC'd before it can be closed, as closing it immediately after use appears to remove the issue.
Bug discovered testing with badger-file, but I cannot be sure where the GC'd object is, and so it could be within the ipfs code, which could mean other datastore implementations were exposed to this.
Fix is commit `Close iterator on spanDone` *only*, the others are small improvements to the codebase I found along the way.
=> fix: Fix invalid (badger) datastore state

.github/workflows/build-dependencies.yml, .github/workflows/check-vulnerabilities.yml, .github/workflows/code-test-coverage.yml, .github/workflows/detect-change.yml, .github/workflows/lint-then-benchmark.yml, .github/workflows/lint.yml, .github/workflows/run-tests.yml, .github/workflows/start-binary.yml, Makefile, go.mod, tests/bench/bench_util.go, tests/bench/storage/utils.go, tests/integration/change_detector.go, tools/cloud/aws/packer/build_aws_ami.pkr.hcl, tools/configs/golangci.yaml, tools/defradb-builder.containerfile, tools/defradb.containerfile
- Resolves #522
- Resolves #1687 
- This is a routine version bump of GoLang, the previous bump was done in (https://github.com/sourcenetwork/defradb/pull/818)
- This PR also introduces a new workflow action (not-mandatory to pass in order to merge) that was showing some vulnerabilities pre-version-bump, all of the vulnerabilities were resolved once the golang version was bumped. In future this trigger will be used to bump golang versions.
- Also updates the golang version for AWS AMI generation.
Note:
- Before the bump we had 13 vulnerabilities: https://github.com/sourcenetwork/defradb/actions/runs/5629964770/job/15255493129?pr=1688
- After the bump: passing with no vulnerabilities.
- Added action that failed with vulnerabilities.
- Bumped version.
- Vulnerabilities were resolved and …
=> chore: Bump to GoLang v1.20

tests/integration/backup/one_to_one/import_test.go, tests/integration/backup/self_reference/import_test.go, tests/integration/backup/self_reference/utils.go, tests/integration/backup/simple/export_test.go, tests/integration/backup/simple/import_test.go
Resolves #1696 
Expands the backup integration tests, and fixes an invalid schema declaration.
Documents https://github.com/sourcenetwork/defradb/issues/1697
I went over the CLI tests too, but found no gaps.
=> test: Expand backup integration tests

api/http/handlerfuncs.go, api/http/handlerfuncs_test.go, cli/schema_list.go, tests/integration/cli/client_schema_add_test.go
Resolves #1705 
Adds some additional `schemaID` and `schemaVersionID` fields to the `schema list` API, both HTTP and CLI
- Manually
- Updated integration tests
- Ubuntu WSL
=> refactor: Schema list output to include schemaVersionID

db/backup.go, db/errors.go, request/graphql/schema/collection.go, tests/integration/backup/one_to_one/import_test.go, tests/integration/backup/self_reference/import_test.go, tests/integration/schema/relations_test.go
Resolves #1697 
This PR add the capability to handle self referencing docs on import.
added integration tests
- MacOS
=> fix(i): Add self reference import handling

db/collection_index.go, db/subscriptions.go
Resolves #1714
Discard index and subscription implicit transactions.
I'm not sure if this was causing any problems, but they should be discarded.
=> fix: Discard index and subscription implicit transactions

core/crdt/composite.go, lens/lens.go, lens/registry.go, tests/integration/schema/migrations/query/with_p2p_test.go
Resolves #1591
Allows documents synced from P2P to migrate (up) by storing the correct schema version id in the datastore on sync.
=> fix(i): Allow documents synced from P2P to migrate

lens/lens.go, lens/registry.go, tests/integration/schema/migrations/query/with_p2p_test.go, tests/lenses/rust_wasm32_set_default/src/lib.rs, tests/lenses/utils.go
Resolves #1719
Enables downgrading of documents via Lens inverses.  Inverse migrations are optional.
This PR is based off of https://github.com/sourcenetwork/defradb/pull/1720 - please review only the last 2 commits here.
There are so far fewer tests than I thought there would be, but I am a bit tired atm, and I may add more whilst waiting on review.  Please suggest any where you think there may be gaps.
~~This IMO breaches the code freeze, but it could be very nice to get it in the release if everyone is happy.~~
Discussed in standup, this should not be merged before the release.
=> feat: Enable downgrading of documents via Lens inverses

api/http/handlerfuncs.go, client/lens.go, datastore/concurrent_txn.go, datastore/concurrent_txt_test.go, datastore/mocks/txn.go, datastore/txn.go, datastore/txn_test.go, db/db.go, db/fetcher/versioned.go, db/txn_db.go, lens/fetcher.go, lens/lens.go, lens/registry.go, lens/txn_registry.go, tests/bench/query/planner/utils.go, tests/integration/lens.go, tests/integration/schema/migrations/query/with_txn_test.go, tests/integration/schema/migrations/with_txn_test.go
Resolves #1649 #1592
Improves the way migrations handle transactions, as well as fixing a couple of concurrency issues:
- Adds locks around the various registry properties, these maps can be accessed concurrently and need to be protected.
- Removes the transaction continuity issue in the client.LenRegistry interface, where db.LensRegistry() returns an object that does not respect the transactionality of the parent store, and takes `txn`s as input parameters to some of its functions. It does this by following the same pattern as `db.db`. (#1649)
- Fixes the bugs in the lens package where migrations set were not visible/accessible until after commit.  They are now visible within the transaction scope. (#1592)
It still does not provide transaction snapshot isolation, I see that issue as …
=> fix: Improve the way migrations handle transactions

client/errors.go, db/collection.go, db/errors.go, db/schema.go, request/graphql/schema/collection.go, request/graphql/schema/errors.go, tests/integration/schema/relations_test.go, tests/integration/schema/simple_test.go, tests/integration/schema/updates/add/field/kind/foreign_object_array_test.go, tests/integration/schema/updates/add/field/kind/foreign_object_test.go
Resolves #1747
Adds support for adding of relational fields to existing schema.
It does not add any syntax magic to make this easy, but it does validate that the provided values are valid (this is pretty much all it does).  Any magic that we add to make the UX tolerable will need to respect these rules anyway, so no time lost there.
Similar to other aspects of the schema migration work, this also does not seek to tidy up the `client.DescriptionFoo` objects, but it does hope to expose and promote that cleanup in the future.
Syntax sugar and `client.DescriptionFoo` cleanup can/will be done later.  Some hopefully within this release.
=> feat: Add support for adding of relational fields

db/collection.go, tests/integration/schema/updates/add/field/kind/foreign_object_test.go
Resolves #1769
Require secondary id field for one-ones.
Simple silly bug caused by developer misunderstanding. Simple fix.
=> fix(i): Require secondary id field for one-ones

db/errors.go, db/schema.go, tests/integration/schema/updates/add/field/kind/foreign_object_array_test.go, tests/integration/schema/updates/add/field/kind/foreign_object_test.go
Resolves #1771
Adds support for PatchSchema relational field `Kind` substitution, and the auto setting of the `Schema` property.
=> feat: Support PatchSchema relational field kind substitution

client/document.go, db/collection.go, db/collection_update.go
Resolves #1786
Unifies collection.save and collection.applyMerge field logic, leaving us with one function through which all document mutations take place.
Also fixes the slightly broken logic for determining whether a field was a foreign relation or not (relying on the field name ending in `_id` is not good enough).
Also expands the value types that `client.Document` can handle.  This is however not the goal of this PR, and they are undocumented (or poorly documented) and likely still incomplete.  Another work item can target this area at some other point in time.
=> refactor(i): Unify collection.save and .applyMerge logic

planner/mapper/mapper.go, planner/planner.go, planner/type_join.go, tests/integration/query/one_to_one/simple_test.go, tests/integration/query/one_to_one/with_clashing_id_field_test.go, tests/integration/query/one_to_one/with_group_related_id_alias_test.go, tests/integration/query/one_to_one/with_group_related_id_test.go
Resolves #1654
Handles the querying of secondary relation id fields.
It does this by joining the related object and copying the dockey value into the secondary related id field.
- ~~Is currently blocked by https://github.com/sourcenetwork/defradb/issues/1769 but can still be reviewed now~~ ~~PR is now based off the fix for that issue (do not review the first commit here).  Will rebase off develop branch before merge.~~ Fix merged to develop, this branch has been rebased onto it.
=> fix: Handle the querying of secondary relation id fields

Makefile
Resolves #1794
Increases the package-levl test timeout.
150s has been breached a couple of times recently, costing dev time.
=> test(i): Increase the package-levl test timeout

db/fetcher/encoded_doc.go
Resolves #1811
Only updates updated fields via update requests by returning a clean document from Decode.
I have tested this via https://github.com/sourcenetwork/defradb/issues/1816 (https://github.com/sourcenetwork/defradb/compare/develop...AndrewSisley:1816-mutation-equivilency?expand=1) however this is a very simple and quite important fix deserving of its own commit/change-log entry in develop, and the test changes are complex and may bog down the merging of the fix.
=> fix: Only update updated fields via update requests

tests/lenses/.cargo/config.toml, tests/lenses/rust_wasm32_copy/Cargo.toml, tests/lenses/rust_wasm32_remove/Cargo.toml, tests/lenses/rust_wasm32_set_default/Cargo.toml
Resolves #1835
Disable multiplexing in the correct file.
It does nothing in its current location, we get a warning logged saying that it is unused - this param belongs in the cargo config file as per this document: https://doc.rust-lang.org/cargo/reference/config.html.
Will hopefully fix the rust dependencies timeouts causing the build to fail every now and then.
=> ci(i): Disable multiplexing in correct file

tests/integration/query/one_to_many/with_dockeys_test.go, tests/integration/test_case.go, tests/integration/utils2.go
Resolves #1830
Tests CreateDoc tests with gql and Collection.Save using the `mutationType` (environment) variable.
=> test(i): Test CreateDoc tests with gql and Collection.Save

.github/workflows/test-collection-named.yml, .github/workflows/test-gql-mutations.yml, Makefile, tests/integration/utils2.go
Resolves #1832
Extends mutation tests with collection.Update and Create calls for the corresponding actions.  Adds another github workflow to run the tests.
I didn't really plan on adding this so soon, but I really want it for https://github.com/sourcenetwork/defradb/issues/935, which I want for https://github.com/sourcenetwork/defradb/issues/1331 - as well as just being nice to test these :)
Is based off https://github.com/sourcenetwork/defradb/pull/1837 - please don't review the first commit here.
=> test(i): Extend mutation tests with col.Update and Create

tests/integration/collection/update/simple/with_deleted_test.go, tests/integration/mutation/create/simple_test.go, tests/integration/mutation/update/field_kinds/array_bool_test.go, tests/integration/mutation/update/field_kinds/array_float_test.go, tests/integration/mutation/update/field_kinds/array_int_test.go, tests/integration/mutation/update/field_kinds/array_string_test.go, tests/integration/test_case.go, tests/integration/utils2.go
Resolves #1849
Skips unsupported mutation types at test level.
Earlier version caused the change detector to fail, as the skip was only executed in the setup stage, not the main/assert stage resulting in test failures. I also think this location makes much more sense, as the skip is a test-level thing, not something that acts at the action-level.
Sorry about the bother caused by this, this should have been spotted by me when I wrote it.
=> test(i): Skip unsupported mutation types at test level

client/document.go, client/document_test.go, tests/integration/mutation/update/field_kinds/array_bool_test.go, tests/integration/mutation/update/field_kinds/array_float_test.go, tests/integration/mutation/update/field_kinds/array_int_test.go, tests/integration/mutation/update/field_kinds/array_string_test.go
Resolves #1842
Correctly handle serialisation of nil field values.
Nil values are not empty byte arrays in CBOR, they need to be handled correctly.
=> fix: Correctly handle serialisation of nil field values

tests/integration/query/one_to_many/with_cid_dockey_test.go, tests/integration/query/one_to_one/with_count_filter_test.go, tests/integration/utils2.go
Resolves #1868
Adds a test for aggregates with a compound relational filter.
Documents https://github.com/sourcenetwork/defradb/issues/1869
I believe this predates the release, and may be a fiddly fix with lots more testing required, so I'm documenting it now and moving on - maybe it will be fixed before the release goes out, but will see.
=> test(i): Test top level agg. wt compound relational filter

tests/integration/utils2.go
N/A
This PR fixes a bug that causes documents to not be correctly refreshed when they are created using alias fields.
`make test:changes`
- MacOS
=> test(i): Remap alias fields when refreshing test documents

client/descriptions.go, db/collection.go, db/collection_update.go, planner/type_join.go, tests/integration/mutation/update/field_kinds/one_to_one/with_self_ref_test.go
Resolves #1914 
Fixes an a bug where an infinite loop may be created when updating a self-referencing one-one relation from the secondary side.
The first commit documents the bug, the second commit fixes it.
=> fix: Infinite loop when updating one-one relation

client/db.go, client/mocks/collection.go, client/mocks/db.go, datastore/concurrent_txn.go, datastore/mocks/txn.go, datastore/multi.go, datastore/store.go, datastore/txn.go, db/db.go, http/client.go, http/client_tx.go, merkle/clock/clock_test.go, merkle/crdt/factory.go, merkle/crdt/factory_test.go, merkle/crdt/merklecrdt_test.go, net/node.go, tests/bench/query/planner/utils.go, tests/clients/cli/wrapper.go, tests/clients/cli/wrapper_tx.go, tests/clients/http/wrapper.go, tests/clients/http/wrapper_tx.go
Resolves #1680
This small refactor adds the `peerstore` to the `multistore`. In doing so, we broaden the types of stores that can be part of the `multistore` by starting from a `ds.Datastore` instead of the more restrictive `DSReaderWriter`
make test showed no change in behaviour.
- MacOS
=> refactor: Add peerstore to multistore

cli/collection.go, cli/errors.go, client/db.go, client/errors.go, client/mocks/db.go, db/collection.go, db/txn_db.go, http/client.go, http/handler_store.go, net/peer_collection.go, net/server.go, planner/commit.go, tests/clients/cli/wrapper.go, tests/clients/http/wrapper.go
Resolves #1963
Changes GetCollectionBySchemaFoo function signatures to return many Collections, instead of single values.
Conceptually these functions were broken and relied on the fact that we cannot yet link multiple collections to the same schema(version)(s).  This changes their signatures and the code that calls them to reflect what they should do long term.
The code that calls these functions now hosts the 'broken' code.  These will still need to change once we add global IDs.
The implementation of these functions will change later in https://github.com/sourcenetwork/defradb/issues/1964.
=> feat: Change GetCollectionBySchemaFoo funcs to return many

tools/defradb.containerfile
Resolves #1983
This PR enables the embedded playground in the DefraDB Docker builds.
Built and pushed image to `docker.io/sourcenetwork/defradb:develop`
- MacOS
=> feat: Enable playground in Docker build

core/key.go, core/parser.go, db/collection.go, db/description/collection.go, db/description/errors.go, db/description/schema.go, db/index_test.go, db/indexed_docs_test.go, db/schema.go, docs/data_format_changes/i1964-reorg-col-desc-storage.md, net/peer_collection.go, net/process.go, tests/integration/backup/one_to_many/export_test.go, tests/integration/backup/one_to_one/export_test.go, tests/integration/net/state/simple/peer/subscribe/with_add_remove_test.go, tests/integration/net/state/simple/peer/subscribe/with_add_test.go
Resolves #1964 #1913 
Reorganises collection description storage so that it actually makes sense.
The existing key/value setup has been replaced with the following keys:
```
[Collection.ID] => json // Json should be stored against an immutable index, i.e. not against `Name`
[Collection.Name] => [Collection.ID]  // This means collection names must be unique
```
We also need the following for the short-term, before Collection.GlobalID gets added, as otherwise if a collection is updated to a new schema version, we lose track of what collection it could be.  The locations that use this have been linked to https://github.com/sourcenetwork/defradb/issues/1085
```
[Collection.SchemaVersionId]/[Collection.ID] => nil
```
With this change the storage setup should fully support multiple collections …
=> refactor: Reorganise collection description storage

cli/cli.go, cli/schema_describe.go, client/db.go, client/mocks/db.go, db/description/schema.go, db/schema.go, db/txn_db.go, http/client.go, http/handler_store.go, http/openapi.go, tests/clients/cli/wrapper.go, tests/clients/http/wrapper.go, tests/integration/schema/get_schema_test.go, tests/integration/schema/simple_test.go, tests/integration/schema/updates/add/field/simple_test.go, tests/integration/test_case.go, tests/integration/utils2.go
Resolves #1993
Adds means to fetch schema.
Adds a bunch of funcs to the clients to allow fetching of schema(versions) defined in the system.  When the set-default stuff got merged, users were no longer guaranteed (at least on init) to be able to view the schema ids they have created, this change allows them to view them when ever they like.
Todo:
=> feat: Add means to fetch schema

Makefile, core/clock.go, core/crdt/composite.go, db/fetcher/versioned.go, merkle/clock/clock.go, net/dag.go, net/dag_test.go, net/process.go, net/server.go, net/server_test.go
Resolves #1066 
This PR change the CRDT merge direction. Originally, when an update arrived over the P2P network, each block was added to the DAG store and merged into the datastore in the order that they were received (newest to oldest block).
With this update, we start my receiving all blocks up to the version that we currently have (or until we reach the root) and then we apply the merge from oldest to newest block. This will enable more CRDT types to be added.
make test
- MacOS
=> refactor: CRDT merge direction

tests/lenses/rust_wasm32_copy/src/lib.rs
Resolves #2036
Fix module relying on closed memory leak.
It only half fixes this, it will be solved properly in lens-vm/lens#62
=> fix: Fix test module relying on closed memory leak

playground/package-lock.json, playground/package.json
✅ This PR was created by the Combine PRs action by combining the following PRs:
#2025 bot: Bump graphiql from 3.0.6 to 3.0.9 in /playground
#2023 bot: Bump eslint from 8.52.0 to 8.53.0 in /playground
#2021 bot: Bump @typescript-eslint/eslint-plugin from 6.9.0 to 6.9.1 in /playground
⚠️ The following PRs were left out due to merge conflicts:
#2022 bot: Bump @vitejs/plugin-react-swc from 3.4.0 to 3.4.1 in /playground
=> bot: Update dependencies (bulk dependabot PRs) 08-11-2023

.github/workflows/test-and-upload-coverage.yml
Resolves #2034
Adds a mac (latest) test run to our test matrix.
This only use the lightest of configurations we have, I think this will catch any/99% issues that we would otherwise miss.
Windows has been broken out to a different ticket, as quite a lot of tests fail on windows and it will take more effort to get working: https://github.com/sourcenetwork/defradb/pull/2033
=> ci: Add mac test runner

.github/workflows/test-and-upload-coverage.yml, config/configfile_test.go, datastore/badger/v4/datastore_test.go, datastore/memory/memory_test.go, db/index_test.go, db/indexed_docs_test.go, http/errors.go, http/server.go, http/server_test.go, logging/logging_test.go, net/client_test.go, net/dialer_test.go, net/node_test.go, net/peer_test.go, tests/integration/backup/simple/export_test.go, tests/integration/backup/simple/import_test.go
Resolves #2032 
Adds a windows test run to our test matrix.
Strongly suggest reviewing commit by commit - I've tried to explain why a bunch of stuff I had to change has been changed in the commit bodies.
- The windows run is consistently slower than the mac/ubuntu ones, worsening our ci wait times
- The below failure appears to happen occasionally:
> error generating coverage report: writing D:\a\defradb\defradb\coverage\covmeta.776b203c66aeebb53e5712fcea6cd9a0: rename from D:\a\defradb\defradb\coverage\tmp.covmeta.776b203c66aeebb53e5712fcea6cd9a01700087389181284400 failed: rename D:\a\defradb\defradb\coverage\tmp.covmeta.776b203c66aeebb53e5712fcea6cd9a01700087389181284400 D:\a\defradb\defradb\coverage\covmeta.776b203c66aeebb53e5712fcea6cd9a0: Access is denied.
I can't spot anything …
=> ci: Add windows test runner

cli/gendocs.go, cmd/gendocs/main.go, tests/gen/cli/errors.go, tests/gen/cli/gendocs.go, tests/gen/cli/gendocs_test.go, tests/gen/cli/util_test.go, tests/gen/gen_auto_configurator.go, tests/gen/gen_auto_option.go, tests/gen/gen_auto_test.go
Resolves #2095
This change adds a new command for generating documents automatically.
It also includes fixes for some overlooked edge cases.
Unit tests and manual command execution with a running defradb node.
- MacOS
=> feat: New cmd for docs auto generation

db/collection_index.go, db/errors.go, db/index.go, db/indexed_docs_test.go, tests/integration/index/create_unique_test.go, tests/integration/index/query_with_unique_index_only_filter_test.go
Resolves #2174 #2175
Forbid `nil` values for fields that are unique-indexed.
Integration and unit tests
- MacOS
=> fix: Handle multiple nil values on unique indexed fields

tests/integration/utils2.go
Resolves #2187
Skip tests in change detector without split.
Previously when there was no split (i.e. only setup actions were present) the last action was being run twice, once in setup, and once during the assertion stage - this went unnoticed until unique secondary indexes started to fail when they added the same doc twice.
=> test(i): Skip tests in change detector without split

db/collection.go, db/description/schema.go, db/schema.go, db/view.go, tests/integration/schema/simple_test.go, tests/integration/view/one_to_one/identical_schema_test.go, tests/integration/view/one_to_one/simple_test_test.go, tests/integration/view/one_to_one/with_restart_test.go
Resolves #2184 #2182
Retain embedded schema within gql types on reload and further GQL modification.
Also refactors the code a little to make it harder to re-introduce (calling `loadSchema` instead of sometimes relying on function vars).
Appears to accidentally solve #2182
Todo:
=> fix(i): Retain embedded schema within gql types on reload

request/graphql/schema/generate.go, tests/integration/view/one_to_many/simple_test.go
Resolves #2191
Don't generate mutation input types for embedded schema.
=> fix(i): Dont build mutation input types for embedded schema

core/crdt/pncounter.go, docs/data_format_changes/i2186-adding-entropy-to-pn-counter.md, merkle/crdt/pncounter.go, tests/integration/mutation/create/crdt/pncounter_test.go, tests/integration/net/state/simple/peer/crdt/pncounter_test.go, tests/integration/query/simple/with_cid_doc_id_test.go
Resolves #2179 
Counters need to be incrementable independently from different nodes. Initially, if two nodes incremented by the same amount from the same synced state, then the update CID would be the same and thus taken as a the same operation when syncing. So starting from 10 if both node A and B increment by 5 simultaneously, because they would generate the same CID for the update, the end result would be 15. We want it to be 20.
This PR adds entropy to the PN Counter delta so that a situation like described above would result in 20.
Note that the entropy is only added on update so that a document can be instantiated on multiple nodes with exactly the same CID.
make test
- MacOS
=> fix: Add entropy to counter CRDT type updates

request/graphql/schema/generate.go, tests/integration/schema/default_fields.go, tests/integration/view/one_to_many/with_introspection_test.go, tests/integration/view/simple/with_introspection_test.go
Resolves #2199
Removes default collection fields from gql view types.
Views should not automatically have these fields.  It will also be impossible to guarantee that they exist once we allow Views to have Lens transforms.
=> fix(i): Remove default collection fields from gql view types

examples/request/user_creation.graphql
N/A
This PR updates the example create request with the new typed input.
N/A
- MacOS
=> fix(i): Update example with typed input

request/graphql/schema/collection.go, request/graphql/schema/errors.go, tests/integration/view/one_to_many/simple_test.go
Resolves #2221
Prevents users from defining double-sided relations in views.
I'm pretty sure this was discussed during the development of views, and accepted as a means of simplifying initial development (lots of stuff gets really complicated if we allow this).  Is just that I only permitted one sided relations, I never blocked off double sided relations.
=> fix(i): Prevent double-sided relations in views

README.md
Resolves #2224 
This PR removes mention of the deprecated `tcpaddr` flag from the readme.
=> fix(i): Remove deprecated tcpaddr flag from readme

.github/workflows/release.yml, .goreleaser.yaml
Resolves #2227 
This PR modifies the release workflow to split the build on the 3 different OS. This is needed now that we use wasmtime and CGO is needed for compilation.
=> chore(i): Split build by OS for release workflow

.github/workflows/release.yml
Resolves #2244 
Fixes the broken id usage (i.e. `cache`) which didn't exist, use the newer `save` and `restore`, add some conditions and flags to fail early if the release fails, and document the cache saving logic (which is not so obvious).
=> ci(i): Fix and document release workflow logic

client/descriptions.go, client/document.go, request/graphql/schema/collection.go, request/graphql/schema/descriptions.go, request/graphql/schema/types/scalars.go, request/graphql/schema/types/scalars_test.go, tests/integration/schema/updates/add/field/kind/invalid_test.go, tests/integration/schema/updates/add/field/kind/json_test.go
Resolves #2243 
This PR adds a JSON scalar type to the schema system
make test
- MacOS
=> feat: Add JSON scalar

cli/utils.go, config/config.go
Resolves #2264 
This PR ensures that the root dir path gets defined prior to looking for a config file. It fixes an issue where the config file wasn't being loaded on node start.
manually tested that a change in the config file would be reflected in the node behaviour.
- MacOS
=> fix: Load root dir before loading config

config/config.go
Resolves #2268
Sorry guys, went one step too far on that last fix (I was the cause of the bug btw). removing the re-added lines cause the a config error on init.
=> fix(i): Revert removal of root dir check in LoadWithRootDIr

README.md, cli/start.go, config/config.go, config/config_test.go, config/configfile_test.go, config/configfile_yaml.gotmpl, net/config.go, net/config_test.go, net/dialer_test.go, net/node.go, net/node_test.go, net/peer_test.go, tests/gen/cli/util_test.go, tests/integration/net/order/utils.go, tests/integration/p2p.go, tests/integration/utils2.go
Resolves #2263
This is part of a larger refactor of the config package.
make test
- MacOS
=> refactor: Decouple net config

client/document.go, client/value.go
Resolves #2274 
Remove unused `Delete` method of `client.Document`
Unit and integration tests.
- MacOS
=> refactor: Remove unused Delete field from client.Document

client/document.go, db/fetcher/errors.go, db/fetcher/indexer.go, db/fetcher/indexer_iterators.go, db/index.go, db/indexed_docs_test.go, docs/data_format_changes/i2161-document-strong-typing.md, docs/data_format_changes/i2276-multiple-nil-for-unique-index-change.md, tests/integration/index/create_unique_test.go, tests/integration/index/query_with_composite_index_only_filter_test.go, tests/integration/index/query_with_index_combined_filter_test.go, tests/integration/index/query_with_index_only_filter_test.go, tests/integration/index/query_with_relation_filter_test.go, tests/integration/index/query_with_unique_composite_index_filter_test.go, tests/integration/index/query_with_unique_index_only_filter_test.go
Resolves #2180
Allow multiple docs with nil value on unique-indexed field.
This change also included few minor query optimizations that involve secondary indexes.
Explain request is slightly adjusted not to increase field fetches count upon fetching indexes.
Unit and integration tests.
- MacOS
=> feat: Multiple docs with nil value on unique-indexed field

planner/delete.go, tests/integration/mutation/delete/with_deleted_field_test.go
Resolves #1846
Marks docs as deleted when querying _deleted in delete mutation.
We could refetch them like we do in update queries, but that seems unnecessary for deletes (updates needs to watch out for impact on aggregates, relations, etc)
=> fix: Mark docs as deleted when querying in delete mut

cli/server_dump.go, cli/start.go, cli/utils.go, config/config.go, node/node.go, node/node_test.go, node/store.go, node/store_test.go
Resolves #2295 
This PR refactors the node setup logic into a new `node` package.
make test
- MacOS
=> refactor: Node config

planner/commit.go, request/graphql/schema/types/commits.go, tests/integration/query/commits/simple_test.go, tests/integration/query/simple/with_version_test.go, tests/integration/results.go, tests/integration/utils2.go
Resolves #2299
This PR fixes a regression bug and adds integration tests to ensure that future changes don't break the expected query results
make test and manual queries
- MacOS
=> fix: Add missing delta payload

.gitignore, cli/view_add.go, client/db.go, client/descriptions.go, db/txn_db.go, db/view.go, http/client.go, http/handler_store.go, planner/datasource.go, planner/lens.go, planner/operations.go, planner/planner.go, planner/view.go, tests/clients/cli/wrapper.go, tests/clients/http/wrapper.go, tests/integration/explain.go, tests/integration/explain/debug/with_view_transform_test.go, tests/integration/test_case.go, tests/integration/utils2.go, tests/integration/view/one_to_many/with_transform_test.go, tests/integration/view/one_to_one/with_transform_test.go, tests/integration/view/simple/with_transform_test.go, tests/lenses/Makefile, tests/lenses/rust_wasm32_filter/Cargo.toml, tests/lenses/rust_wasm32_filter/src/lib.rs, tests/lenses/rust_wasm32_prepend/Cargo.toml, tests/lenses/rust_wasm32_prepend/src/lib.rs, tests/lenses/utils.go
Resolves #2070
Adds support for views with Lens transforms.
=> feat: Add support for views with Lens transforms

.goreleaser.yaml
Resolves #2332 
This PR adds the `latest` tag to the Github container registry release from GoReleaser.
=> fix: Add `latest` image tag for ghcr

Makefile, tests/change_detector/change_detector_test.go
Resolves #2351
Removes lens test split in make file.
`make test` and friends will now compile the lens modules and execute the lens related tests.  Note, the rustup dependency is already noted in CONTRIBUTING.md.
=> ci(i): Remove lens test split in make file

client/document.go, client/document_test.go, client/errors.go, tests/integration/mutation/create/field_kinds/field_kind_json_test.go
Resolves #2370 
This PR adds validation to JSON fields.
make test
- MacOS
=> fix: Add validation to JSON fields

request/graphql/schema/collection.go, request/graphql/schema/manager.go, request/graphql/schema/types/descriptions.go, request/graphql/schema/types/types.go
Resolves #2312 
This PR adds the missing directive definitions (`@crdt`, `@primary`, `@relation`) to GraphQL
tested in GraphQL client
- MacOS
=> fix: Add missing directive definitions

connor/connor.go, connor/ilike.go, connor/ilike_test.go, connor/like.go, connor/nilike.go, connor/nilike_test.go, connor/nlike_test.go, db/fetcher/indexer_iterators.go, request/graphql/schema/types/base.go, request/graphql/schema/types/descriptions.go, tests/integration/index/query_with_composite_index_field_order_test.go, tests/integration/index/query_with_index_combined_filter_test.go, tests/integration/index/query_with_unique_composite_index_filter_test.go, tests/integration/index/query_with_unique_index_only_filter_test.go, tests/integration/query/one_to_many/with_filter_test.go, tests/integration/query/simple/with_filter/with_like_string_test.go, tests/integration/query/simple/with_filter/with_nlike_string_test.go, tests/integration/schema/aggregates/inline_array_test.go
Resolves #2367 
This PR adds support for case insensitive like and not-like operators. This was requested by a partner.
make test
- MacOS
=> feat: Add case insensitive `like` operator

cli/collection_describe.go, client/db.go, db/collection.go, tests/integration/schema/updates/with_schema_branch_test.go
Resolves #2371 
This PR updates the behaviour of `getCollections` to return inactive collections if a specific version is requested even if the `--get-inactive` flag hasn't been set.
make test
- MacOS
=> fix: Update GetCollections behaviour

http/handler_lens.go, request/graphql/parser/request.go, tools/configs/golangci.yaml
Resolves #2382 
This PR enables the `nilness` linter and fixes a few issues caught by it.
`make lint`
- MacOS
=> tools(i): Enable nilness linter

client/db.go, db/txn_db.go
Resolves #2384
Makes returned collections respect explicit transactions.
I have not added any new tests in this PR as there is not much time before the release, there is currently no test actions to do facilitate this, and it is a fairly safe change.  I might add tests in a new PR before 0.10.0 is cut if there is time.
=> fix: Make returned collections respect explicit transactions

docs/data_format_changes/i2386-no-change-tests-updated.md, tests/integration/query/one_to_many/with_cid_doc_id_test.go, tests/integration/query/simple/with_cid_doc_id_test.go, tests/integration/utils.go
Resolves #2386
Converts old update tests to newer framework.
=> test(i): Convert old update tests to newer framework

http/server.go, http/server_test.go, net/peer.go, node/node.go
Resolves #2308 
Resolves #2309
This PR re-adds startup logs showing the P2P addresses and HTTP endpoint of the node.
manually tested in the CLI
- MacOS
=> fix: Add missing logs at startup

.github/workflows/release.yml
Resolves #2394 
This PR moves the cache action in the release workflow to be after the goreleaser action. After the last release, we changed the cache action to use `action/cache/save` instead of just `action/cache`. The difference is that `action/cache` acts like a defer function and  gets actioned at the end of a job. `action/cache/save` is meant to be more granular and tries to save when called. This caused a situation where it tried to save in the cache a path that didn't exist.
tested the workflow on my personal fork
=> fix(i): Move cache action after goreleaser action

lens/fetcher.go, lens/history.go, lens/lens.go, tests/integration/schema/migrations/query/with_p2p_schema_branch_test.go, tests/integration/schema/migrations/query/with_schema_branch_test.go, tests/integration/utils2.go
Resolves #2293
Adds Defra-Lens support for branching schema.
Defra will now be able to handle migrations for a branching schema version DAG.
=> feat: Add Defra-Lens support for branching schema

client/value.go
Resolves #2444
Rewrites convertImmutable.
=> refactor: Rewrite convertImmutable

.github/workflows/test-and-upload-coverage.yml
Resolves #2449 
- Disable windows build until wasmtime-go is fixed
- To enable back just uncomment the lines in: `.github/workflows/test-and-upload-coverage.yml`
=> ci(i): Disable windows build

client/errors.go, db/collection.go, db/errors.go, request/graphql/schema/descriptions_test.go, request/graphql/schema/relations.go, tests/gen/gen_auto_test.go, tests/integration/backup/one_to_one/export_test.go, tests/integration/backup/one_to_one/import_test.go, tests/integration/explain/fixture.go, tests/integration/index/query_with_relation_filter_test.go, tests/integration/mutation/create/field_kinds/one_to_one_to_one/utils.go, tests/integration/mutation/delete/field_kinds/one_to_one_to_one/utils.go, tests/integration/schema/one_one_test.go, tests/integration/schema/relations_test.go, tests/integration/view/one_to_one/with_transform_test.go, tests/predefined/gen_predefined_test.go
Resolves #2461
Forces the explicit declaration of the primary side of one-one relation fields in SDL.
PatchSchema already forces this and needed no change.
Note: The error usage in the db package may be removed very soon in https://github.com/sourcenetwork/defradb/issues/2451 along with the entire `request/graphql/schema/relations.go` file.
=> feat: Force explicit primary decl. in SDL for one-ones

tests/integration/test_case.go, tests/integration/utils2.go
Resolves #2494 
This PR adds a test flag set via an environment variable to skip any tests that involve network actions.
`make test`
- MacOS
=> test: Add flag to skip network tests

db/collection_index.go, db/index.go, tests/integration/index/update_unique_composite_test.go, tests/integration/index/update_unique_test.go
Resolves #2510 
This PR adds a check to the index validation step where if the resulting KV pair is the same on update as the previous KV pair, the outcome will be an no-op instead of an index existing error.
make test
- MacOS
=> fix: Allow update when updating non-indexed field

tests/integration/backup/one_to_one/import_test.go, tests/integration/net/state/simple/peer/with_create_add_field_test.go, tests/integration/query/one_to_many/with_cid_doc_id_test.go, tests/integration/query/one_to_many/with_group_related_id_alias_test.go, tests/integration/query/one_to_many/with_group_related_id_test.go, tests/integration/query/simple/with_order_test.go, tests/integration/schema/migrations/query/with_p2p_schema_branch_test.go, tests/integration/utils2.go, tests/integration/view/simple/with_filter_test.go
Resolves #2435
Asserts that all expected properties are returned in integration test queries.
Is quite bad that this was missed for so long, luckily none of the bad tests passing because of it failed when their queries were corrected :sweat_smile:
=> test(i): Assert all expected props are returned in tests

client/README.md, client/data_definition.md
Resolves #2538
Adds data definition document, documenting how data is defined.
It is targeted at us, and anyone looking to embed defradb in their application.
=> docs: Add data definition document

tests/integration/issues/2566_test.go, tests/integration/issues/2569_test.go, tests/integration/issues/README.md, tests/integration/mutation/update/crdt/pncounter_test.go, tests/integration/test_case.go, tests/integration/utils2.go
Resolves #2565
Fixes a faulty PnCounter overflow test which was doing a no-op whilst pretending to increment.
Adds a test for negative float64 overflows, and two tests documenting the newly found https://github.com/sourcenetwork/defradb/issues/2566 in a new `issues` directory.
I don't think I see #2566 as a release blocker, but no strong feelings there yet.
There is more info in the commit messages RE each change.
=> test(i): Fix PnCounter overflow tests

db/fetcher/fetcher.go, planner/filter/complex.go, planner/filter/complex_test.go, planner/type_join.go, tests/integration/query/one_to_one/with_filter_test.go
Resolves #2571
This PR adds a check post doc filtering in the fetcher to see if we need to rely on the external conditions instead to ensure a valid filtering operation. This is specially important when filtering with logical operators `_and` and `_or`.
make test
- MacOS
=> fix: Add check to filter result for logical ops

planner/filter/complex.go, planner/filter/complex_test.go, planner/planner.go, planner/type_join.go, tests/integration/index/query_with_compound_filter_relation_test.go
Resolves #2572
Handles compound filters targeting related indexed fields, and one-many joins from the many side.
The invertableJoin issue may be affecting non indexed joins.
First commit documents the existing behaviour, second commit fixes it.
There is another issue in this space not solved by this PR: https://github.com/sourcenetwork/defradb/issues/2574
=> fix: Handle compound filters on related indexed fields

tests/integration/index/query_with_compound_filter_relation_test.go
Resolves #2580
Fix dataless compound relational index filter tests.
Spotted by @islamaliev here: https://github.com/sourcenetwork/defradb/pull/2575/files#r1587833621
=> test(i): Fix dataless compound relational index filter tests

planner/type_join.go, tests/integration/index/query_with_relation_filter_test.go
Resolves #2574
Return correct results from one-many joins filtered on an indexed field on the many side.
The invertibleTypeJoin doesn't support the inversion of one-many joins and was converting them into one-one joins.
This means that the index is no longer used if targeting the many side: https://github.com/sourcenetwork/defradb/issues/2578 (this support can be added after the release).
=> fix: Return correct results from one-many indexed filter

tests/integration/acp/query/avg_test.go, tests/integration/acp/query/count_test.go, tests/integration/acp/query/fixture.go, tests/integration/acp/query/relation_objects_test.go
Resolves #2474 and #2475
Add integration tests for ACP on relation objects and `_avg` and `_count` methods.
=> test: Add more ACP integration tests

events/db_update.go
Resolves #2597
Documents the Event Update struct.
It is a public type, and hopefully this will save some future head scratching :)
=> docs: Document Event Update struct

internal/planner/type_join.go, tests/integration/index/docs.go, tests/integration/index/query_with_relation_filter_test.go, tests/integration/test_case.go, tests/predefined/README.md
Resolves #2590 and #2600
Make join fetch all secondary docs of a fetched-by-index primary doc.
=> fix: Remove limit for fetching secondary docs

internal/db/collection_index.go, internal/db/errors.go, tests/integration/acp/index/create_test.go, tests/integration/acp/index/fixture.go, tests/integration/acp/index/query_test.go, tests/integration/acp/index/query_with_relation_test.go
Resolves #2365
Enable secondary indexes with ACP.
=> feat: Enable sec. indexes with ACP

cli/server_dump.go, node/node.go, node/store.go, tests/bench/bench_util.go, tests/integration/db.go, tests/integration/events/utils.go, tests/integration/net/order/utils.go
Resolves #2634
Tests node pkg constructor via integration test suite instead of bypassing it and directly creating `db` instances via the `db` package.
=> test: Test node pkg constructor via integration test suite

tests/integration/db.go
Resolves #2643
Don't setup http and p2p by default in test suite.
This is a regression I introduced in https://github.com/sourcenetwork/defradb/pull/2641 (sorry for the bother) - we set p2p and http up later.  As the new, unused, P2P and http servers werent cleaned up at the end of the test, this had quite a bad effect on test suite memory consumption.
Later, I think the surrounding code that sets up p2p and http could probably be changed later to make better use of `node.New`, but IMO this is good enough for now (we have other things to do).
=> test(i): Don't setup http and p2p by default in test suite

cli/start.go, node/node.go, node/node_test.go, tests/integration/db.go
Resolves #2642 
This PR fixes an issue where node subsystem options were not composable.
`make test`
- MacOS
=> fix: Make node options composable

.github/workflows/check-cli-documentation.yml
Resolves #2165
- Detects if cli documents need updating.
- If Documentation is up to date the action passes, else fails.
- Run `make docs` or `make docs:cli` to generate the documentation.
- Introducing as a non-required check, but would argue it should be required.
- Manually testing through action run and by using `act` utility.
- Failed action: https://github.com/sourcenetwork/defradb/actions/runs/9214068142/job/25349425467?pr=2647
- WSL2
=> ci(i): Add workflow to ensure cli docs are in sync

acp/acp_local.go, acp/acp_local_test.go, acp/source_hub_client.go, net/peer_test.go, node/acp.go
Resolves #2655
Extracts Defra specific logic from the ACPLocal type so that it may be re-used for SourceHub ACP.
None of the code has changed, it's just moved around.
I'm opening a PR now, as a lot of us (including Bruno) are working in this space, and merging refactors like this asap tends to minimise conflicts.
The (WIP) source hub implementation can be found here: https://github.com/sourcenetwork/defradb/pull/2657
=> refactor: Extract Defra specific logic from ACPLocal type

datastore/txn_test.go
Resolves #2671 
We noticed that our in-memory store and badger behave a little differently on transaction conflicts. This PR simply documents this behaviour difference with added unit tests. The next step will be to decide if our in-memory store should be modified to behave the same way.
unit tests
- MacOS
=> test(i): Add txn conflict documentation

tests/integration/index/query_with_compound_filter_relation_test.go, tests/integration/mutation/create/field_kinds/one_to_many/with_alias_test.go, tests/integration/mutation/create/field_kinds/one_to_many/with_simple_test.go, tests/integration/test_case.go, tests/integration/utils2.go
Resolves #2681
Adds a relation substitute mechanic to tests, allowing us to not worry about doc ids in tests that don't need to care about the exact string.
Only converts a handful of tests to the new system, I don't think we should actively spend large chunks of time migrating to the new system - we can just write new tests using this where appropriate, and passively convert existing when convenient.
=> test: Add relation substitute mechanic to tests

client/normal_nil.go, client/normal_value_test.go, client/schema_field_description.go, docs/data_format_changes/i2670-sec-index-on-relations.md, internal/db/collection_index.go, internal/db/index.go, internal/planner/explain.go, internal/planner/mapper/mapper.go, internal/planner/mapper/select.go, internal/planner/planner.go, internal/planner/select.go, internal/planner/type_join.go, tests/integration/explain/execute/with_count_test.go, tests/integration/index/query_with_relation_filter_test.go
Resolves #2601 #2578 #2577
Enables fetching related objects via secondary indexes.
It also fixes a bug with queries that contain multiple aggregates on the same collection.
Note: I will add some more tests
=> feat: Sec. indexes on relations

.github/workflows/check-cli-documentation.yml, .github/workflows/check-http-documentation.yml, Makefile, docs/website/references/http/openapi.json
Related #510 
Resolve #2677
- Detect OpenAPI / HTTP documentation is always up to date.
- Generate open-api docs in the appropriate dir.
- using `act` tool
- manually introducing a change and seeing the action fail: https://github.com/sourcenetwork/defradb/actions/runs/9359749777/job/25763961265?pr=2678
- WSL2 instance
=> docs: Add http/openapi documentation & ci workflow

.github/workflows/test-and-upload-coverage.yml, cli/server_dump.go, cli/start.go, client/lens.go, docs/config.md, go.mod, go.sum, http/client_lens.go, http/handler_ccip_test.go, internal/db/config.go, internal/db/db.go, internal/db/db_test.go, internal/lens/registry.go, internal/lens/txn_registry.go, net/node_test.go, net/peer_test.go, node/errors.go, node/lens.go, node/lens_wasmer.go, node/lens_wasmtime.go, node/lens_wazero.go, node/node.go, tests/clients/cli/wrapper_lens.go, tests/gen/cli/util_test.go, tests/integration/db.go, tests/integration/lens.go, tools/defradb.containerfile
Resolves #2683
Allows lens runtime selection via config/cli param.
Also adds CI jobs to the matrix to test wasmer and wazero.  I was hoping it would solve the windows build issue, but still no joy there :(
=> feat: Allow lens runtime selection via config

cli/request.go, client/db.go, http/client.go, http/handler_ccip.go, http/handler_store.go, internal/db/request.go, internal/db/subscriptions.go, tests/clients/cli/wrapper.go, tests/integration/utils2.go
Resolves #2685 
This PR replaces subscription event publishers with a simple go channel. This is a pre-requisite to a follow up events package refactor.
`make test`
- MacOS
=> refactor: Replace subscription events publisher

docs/data_format_changes/i2696-support-encryption-for-counters.md, internal/core/block/block.go, internal/core/crdt/counter.go, internal/core/crdt/errors.go, internal/core/crdt/ipld_union.go, internal/merkle/crdt/counter.go, internal/merkle/crdt/merklecrdt.go, tests/integration/query/simple/with_cid_doc_id_test.go
Resolves #2696 
This PR changes the counter CRDTs to make them support the document encryption feature. They previously stored their values as concrete types (int64 and float64) instead of bytes. Storing them as bytes allow them to be stored plainly or encrypted.
make test
- MacOS
=> refactor: Change counters to support encryption

datastore/concurrent_txn.go, datastore/mocks/txn.go, datastore/txn.go, datastore/txn_test.go, http/client_tx.go, tests/bench/query/planner/utils.go, tests/clients/cli/wrapper_tx.go, tests/clients/http/wrapper_tx.go
Resolves #2707
This PR adds async versions for all transaction callbacks.
`make test`
- MacOS
=> feat: Add async transaction callbacks

cli/config.go, cli/config_test.go, cli/root.go, cli/start.go, cli/utils.go
Resolves #2712 
This PR fixes a race condition found in #2700 
`make test`
- MacOS
=> fix: Race condition when testing CLI

go.mod, go.sum
Resolves #2714 
This is a simple update of the pubsub-rpc version. A fix was done on our fork of this package that removes the annoying error log that we would get.
```
2024-06-12T20:51:37.954-0400	ERROR	psrpc	go-libp2p-pubsub-rpc@v0.0.13/rpc.go:350	subcription message handler: decoding response id: invalid cid: cid too short
```
=> chore(i): Update pubsub rpc version

internal/db/collection_define.go, internal/db/definition_validation.go, internal/db/errors.go, internal/db/schema.go, internal/db/view.go, tests/integration/collection_description/updates/copy/name_test.go, tests/integration/collection_description/updates/replace/name_test.go, tests/integration/schema/get_schema_test.go, tests/integration/schema/migrations/query/simple_test.go, tests/integration/schema/migrations/query/with_doc_id_test.go, tests/integration/schema/migrations/query/with_inverse_test.go, tests/integration/schema/migrations/query/with_p2p_schema_branch_test.go, tests/integration/schema/migrations/query/with_p2p_test.go, tests/integration/schema/migrations/query/with_restart_test.go, tests/integration/schema/migrations/query/with_set_default_test.go, tests/integration/schema/migrations/query/with_txn_test.go, tests/integration/schema/migrations/query/with_update_test.go, tests/integration/schema/migrations/simple_test.go, tests/integration/schema/one_one_test.go, tests/integration/schema/updates/add/field/create_update_test.go, tests/integration/schema/updates/add/field/simple_test.go, tests/integration/schema/updates/add/simple_test.go, tests/integration/schema/updates/copy/field/simple_test.go, tests/integration/schema/updates/copy/simple_test.go, tests/integration/schema/updates/remove/simple_test.go, tests/integration/schema/updates/replace/simple_test.go, tests/integration/schema/updates/with_schema_branch_test.go, tests/integration/schema/with_update_set_default_test.go
Resolves #2537
Reworks definition validation, standardizing the rule signatures, allowing rule reuse across different contexts, and hopefully improving their readability.  Performance of the rules will have decreased slightly, but on col/schema update that is unimportant, performance of `createCollections` (called when creating via SDL docs) has probably improved slightly due to a reduction in datastore calls.
This is largely in preparation for https://github.com/sourcenetwork/defradb/issues/2401 and the removal/simplification of `SetActiveVersion`.
=> refactor: Rework definition validation

datastore/badger/v4/datastore_test.go, datastore/memory/txn.go, datastore/memory/txn_test.go, datastore/txn_test.go
Resolves #2673 
This PR fixes the incorrect merge conflict in our memory store.
make test
- MacOS
=> fix: Resolve incorrect merge conflict

.github/workflows/test-and-upload-coverage.yml
Resolves #2735 
In this PR we cache go and rust build/dep states, and restore them if an action run has same dependency graph. Go cache is around 877 MB and cargo/rust cache is about 189MB (99MB for macos) so we can roughly have room for 5 caches (x1 for linux and x1 for macos) before a cache is dropped / lost.
Notes:
- Github gives us 10GB of cache storage by default.
- Rather than going with the standard practice of using lockfiles to generate the caching key we will use the mod and toml files, in order to maximize cache hits. Incase troublesome we can go back to lockfiles.
- This change does not help the change detector. IMO change detector should move to a separate job, or a new workflow file. (opened https://github.com/sourcenetwork/defradb/issues/2736)
- Without cache run (current …
=> ci: Cache dependencies to speed up test runs

go.mod, go.sum, internal/db/merge.go, net/node.go, net/peer.go, net/server.go
Resolves #2737
This PR bumps corelog to v0.0.8 and converts error logs to `ErrorE` or `ErrorContextE`.
`make test`
- MacOS
=> fix(i): Convert error logs to `ErrorE` func

tests/change_detector/utils.go, tests/integration/explain.go, tests/integration/explain_result_asserter.go, tests/integration/results.go, tests/integration/state.go, tests/integration/test_case.go, tests/integration/utils2.go
Resolves #2739
Allows test harness to execute benchmark tests as well as normal-tests.
Broken out of https://github.com/sourcenetwork/defradb/issues/2545 - is a good change independent of that though anyway and will allow us to use the integration test actions in benchmarks.
=> test: Allow test harness to execute benchmarks

datastore/memory/txn.go, datastore/memory/txn_test.go, datastore/txn_test.go
Resolves #2741 
This PR fixes a bug with the memory store where `basicTxn.Query` did not consider the transaction version when querying. This means that it could return KVs created after the transaction was initiated.
Note that the first commit documents the bug.
make test
- MacOS
=> fix: Add version check in basicTxn.Query

docs/data_format_changes/i2746-use-node-representation.md, internal/core/block/block.go, internal/core/block/block_test.go, internal/db/merge_test.go, net/sync_dag.go, tests/integration/events/simple/with_update_test.go, tests/integration/mutation/create/with_version_test.go, tests/integration/query/commits/simple_test.go, tests/integration/query/commits/with_cid_test.go, tests/integration/query/commits/with_depth_test.go, tests/integration/query/commits/with_doc_id_cid_test.go, tests/integration/query/commits/with_doc_id_count_test.go, tests/integration/query/commits/with_doc_id_field_test.go, tests/integration/query/commits/with_doc_id_limit_offset_test.go, tests/integration/query/commits/with_doc_id_limit_test.go, tests/integration/query/commits/with_doc_id_order_limit_offset_test.go, tests/integration/query/commits/with_doc_id_order_test.go, tests/integration/query/commits/with_doc_id_test.go, tests/integration/query/commits/with_doc_id_typename_test.go, tests/integration/query/commits/with_field_test.go, tests/integration/query/commits/with_group_test.go, tests/integration/query/latest_commits/with_doc_id_field_test.go, tests/integration/query/latest_commits/with_doc_id_test.go, tests/integration/query/one_to_many/with_cid_doc_id_test.go, tests/integration/query/simple/with_cid_doc_id_test.go, tests/integration/query/simple/with_version_test.go
Resolves #2745
This PR ensures that the node being passed to the link system is in it's representation form. This will allow the use of optional fields.
Node that the 2 added `block` unit tests are there to cover when the optional `isEncrypted` field will be added to `Block` ipld schema.
make test
- MacOS
=> fix: Use node representation for Block

internal/db/collection_define.go
Resolves #2764
Return slice of correct length from db.AddSchema, values are appended to this slice later in the function, but the result declaration is done as if they will be set by index.
Bug also affected `db.AddView`.
~~I'll create a ticket to allow us to test this properly (the results of `AddSchema and `AddView` are never asserted by our integration tests atm).~~ Ticket created: https://github.com/sourcenetwork/defradb/issues/2766
=> fix: Return slice of correct length from db.AddSchema

acp/identity/errors.go, acp/identity/generate.go, acp/identity/identity_test.go, cli/cli.go, cli/identity.go, cli/identity_new.go, cli/identity_new_test.go, docs/website/references/cli/defradb_identity.md, docs/website/references/cli/defradb_identity_new.md
Resolves #2554 
Now that the `core_acp` work is merged the identity generation becomes much more simple, with a `did` instead of `source address`. This util command can be handy to quickly generate new identity pairs with their did.
Issue the command:
```
$ defradb identity new
```
Output:
```json
{
"PrivateKey": "8wsOdJZCg06ISJxBqUyrD1ovDF5WgJJrSup2i4avnuU=",
"PublicKey": "BG6dw3UW3rv+IiTXfL0LXvACw7Qz3DSBy1KmS/eSNrsrRkToBsize7zp+xwFrelPylOPgZguG7ZmirAtTaY89ow=",
"DID": "did:key:z7r8oqgz72xy7Z7V5WGF21iWc7EY8vCpjZA1nGugoKjGeppeMkqeD7FV5AxEQAnciBz5vk5c2zrTZytofJNM8ZxyBzSpT"
}
```
- cli test
- unit tests
- WSL2
=> feat: Ability to generate a new identity

Makefile
Resolves #2771
Runs all the developer make commands in one command.
locally
- WSL2
=> tools(i): Make one command do all the steps

acp/identity/generate.go, cli/identity_new.go, docs/website/references/cli/defradb_identity_new.md
Resolves #2770 
- Return the priv/pub keys in hex
- WSL2
=> fix: Change new identity keys to hex format

Makefile, client/mocks/collection.go, client/mocks/db.go, datastore/mocks/dag_store.go, datastore/mocks/ds_reader_writer.go, datastore/mocks/results.go, datastore/mocks/root_store.go, datastore/mocks/txn.go, internal/db/fetcher/mocks/encoded_document.go, internal/db/fetcher/mocks/fetcher.go, tools/configs/mockery.yaml
Resolves #2775
- Remove the deprecated config option that causes errors.
- Bump mockery to `2.43.0`
locally
- WSL2
=> chore(i): Bump mockery to `v2.43.0` & fix deprecated config

cli/keyring.go, cli/keyring_generate.go, cli/keyring_generate_test.go, cli/utils.go, docs/website/references/cli/defradb_keyring.md, docs/website/references/cli/defradb_keyring_generate.md
Resolves #2759
Resolves #2758
Resolves #2757
This PR adds more logs to the keyring to improve the user experience.
- unit test
- MacOS
=> fix: Keyring output

tests/integration/net/one_to_many/peer/with_create_update_test.go, tests/integration/utils2.go
Resolves #2785
Support asserting on doc index in test results.
PR does not seek to propagate it's usage, only to permit it's usage.
I also checked that it fails correctly if the results do not pair up.
=> test: Support asserting on doc index in test results

tests/integration/mutation/update/field_kinds/one_to_many/with_alias_test.go
Resolves #1854
Removes a duplicate test.
I think this bug might have been resolved by the validation refactor a few weeks ago and I never spotted the test-split when tweaking the expected result.
=> test: Remove duplicate test

.github/workflows/build-dependencies.yml, .github/workflows/build-then-deploy-ami.yml, .github/workflows/check-documentation.yml, .github/workflows/check-mocks.yml, .github/workflows/check-tidy.yml, .github/workflows/check-vulnerabilities.yml, .github/workflows/combine-bot-prs.yml, .github/workflows/lint-then-benchmark.yml, .github/workflows/lint.yml, .github/workflows/preview-ami-with-terraform-plan.yml, .github/workflows/release.yml, .github/workflows/start-binary.yml, .github/workflows/test-and-upload-coverage.yml, .github/workflows/validate-containerfile.yml, .github/workflows/validate-title.yml
Resolves #2778
- Similar to #990
- Update all actions to `node20` versions
- There was a bug the way we were using artifacts previously such that it would overwrite some generated code coverage reports due to artifact name clashing, this was caught as the behavior of "artifact name clashing" now causes error instead of "merging" them. The fix is in the last commit, which will now ensure "more" accurate coverage as the missing 3 reports are also included.
- This should be done outside this PR, made an issue here: https://github.com/sourcenetwork/defradb/issues/2781 
- `act` tool
- ci
- WSL2
=> ci(i): Bump all gh-action versions to support node20

.github/workflows/check-data-format-changes.yml, .github/workflows/test-and-upload-coverage.yml
Resolves #2736
- Move change detection to a separate workflow to not block code coverage upload to be dependent / blocked by it.
- More reasons in the issue (#2736) on why we want this.
- Manually
- WSL2
=> ci(i): Make change detector an independent workflow

.github/workflows/test-and-upload-coverage.yml
- Remove redundant matrix rule that is repeated (1st commit)
- Move all non-ubuntu special rules at the bottom
- `act` tool
- ci
- WSL2
=> ci(i): Remove redundant matrix rule that is repeated

README.md
Resolves #2792
Removes the reference to client ping from readme.  The ping command no longer exists.
Tested locally, command fails with `Error: Get "http://127.0.0.1:9181/api/v0/collections": dial tcp 127.0.0.1:9181: connect: connection refused` if the server is down.
=> docs: Remove reference to client ping from readme

tests/integration/results.go, tests/integration/schema/simple_test.go, tests/integration/test_case.go, tests/integration/utils2.go
Resolves #2766
Allows assertion of AddSchema results.
PR Does not attempt to spread it's usage (out of scope).
=> test: Allow assertion of AddSchema results

.github/workflows/release.yml, .goreleaser.yaml
Resolves #2797 
This PR updates the Go Releaser to version 2.
(*replace*) Describe the tests performed to verify the changes. Provide instructions to reproduce them.
locally and in through the release action on a fork.
- MacOS
=> ci(i): Update go releaser

internal/request/graphql/schema/collection.go, tests/integration/results.go, tests/integration/schema/one_many_test.go
Resolves #961
Allows primary field declarations on one side of one-many.
Declaring it as primary doesn't do anything, but there is no reason it shouldn't be permitted and it definitely shouldn't have errored the way it did.
=> fix: Allow primary field declarations on one-many

internal/request/graphql/schema/collection.go, tests/integration/schema/one_many_test.go
Resolves #2620
Support one-many self joins without primary directive.
=> fix: Support one-many self joins without primary directive

tests/integration/utils2.go
Resolves #2812 
This fixes two issues in `refreshDocuments`.
- `DocIndex`es were not accounted for in refresh documents, this was introduced a while ago and lay hiding until recently
- Creating multiple docs in a single action was not handled
`refreshDocuments` is called in the second half of the change detector to populate the test document cache with docs created in the setup stage.
The hardcoding of cyrpto stuff was discussed as a problem for the change detector, however that is innocent - I think I was looking at an older CI log originally.  I did manage to remove the test cyrpto stuff (#2801), but it requires cleanup and doesn't really belong in this PR.
=> test: Fix refreshing of docs in change detector

go.mod, go.sum
Resolves #2823
Bump grpc version. 1.64 has a security issue
=> chore: Bump grpc version

acp/README.md, acp/acp.go, acp/source_hub_client.go, internal/db/errors.go, internal/db/p2p_replicator.go, internal/db/p2p_schema_root.go, internal/db/p2p_schema_root_test.go, tests/integration/acp.go, tests/integration/acp/p2p/replicator_test.go, tests/integration/acp/p2p/subscribe_test.go, tests/integration/db.go, tests/integration/state.go
Resolves #2366
Handles P2P with SourceHub ACP.
Local ACP remains blocked off, as documents synced would essentially become public unless encrypted.
The testing assumes that a distributed SourceHub chain would be tested in the SourceHub repo, and so it doesn't bother spinning up a chain per node and dealing with SourceHub sync stuff.  Long term we'll want some Defra-based testing around this, but I think we can get away without it.  Feel very free to argue against this :)
=> feat: Handle P2P with SourceHub ACP

client/document.go, client/schema_field_description.go, internal/db/collection.go, internal/db/definition_validation.go, internal/planner/mapper/mapper.go, internal/planner/type_join.go, internal/request/graphql/schema/collection.go, internal/request/graphql/schema/generate.go
Resolves #2356
Removes IsObjectArray.
As well as causing confused code, and an overly-large interface, where their are multiple overlapping ways to check the same thing, this func also dirties the solution for #2493 and #2619.
PR is marked as a feature as it is a public change, could be called 'fix', I think it is a bit vague here give me a shout if you have a strong preference.
=> feat: Remove IsObjectArray

.github/workflows/test-and-upload-coverage.yml
Related #2865 
This PR locks the sourcehub version until the dev branch is stable again.
CI
- MacOS
=> fix(i): Lock sourcehub version

internal/db/fetcher/indexer.go, tests/integration/index/query_with_relation_filter_test.go
Resolves #2862
Handles multiple child index joins.
Init is called multiple times (IIRC when joining in this direction it is called 1+NPrimaryDocs times) and the state was preserved between calls.  The new `resetState` func duplicates the overwriting of props set in init, but I see that as worth it (very cheap, and means devs don't have to care what is set outside of the constructor).
=> fix: Handle multiple child index joins

tests/integration/index/query_with_relation_filter_test.go, tests/integration/query/one_to_many_to_many/joins_test.go, tests/integration/utils2.go
Resolves #2870
Enables asserting using `testUsilts.NewDocIndex` on child documents
=> test: Add assert on DocIndex for child documents

tests/integration/subscription/subscription_test.go, tests/integration/test_case.go, tests/integration/utils2.go
Resolves #2873
This PR is small refactor of the subscription tests to make it easier to test ordering of results and eventually multiple selections within the results.
`make test`
- MacOS
=> refactor(i): Subscription test results

internal/request/graphql/schema/descriptions.go, internal/request/graphql/schema/generate.go
Resolves #2868
This PR fixes the create mutation return type.
manually tested in playground
- MacOS
=> fix: Create mutation introspection

internal/db/fetcher/indexer.go, internal/db/fetcher/indexer_iterators.go, tests/integration/index/query_with_index_only_filter_test.go
Resolves #2916
Check if given filter condition is empty before proceeding with secondary index fetching.
=> fix: No panic if filter condition on indexed field is empty

go.mod, internal/db/fetcher/indexer_iterators.go, internal/encoding/encoding.go, internal/encoding/field_value.go, internal/encoding/time.go, internal/encoding/type.go, tests/integration/index/create_unique_test.go, tests/integration/index/query_with_index_on_datetime.go, tests/integration/index/query_with_unique_index_only_filter_test.go
Resolves #2914
Make indexes handle time.Time type as well.
For this encoding/decoding of time type is added to encoding package.
=> feat: Enable indexing for DateTime fields

client/document.go, client/value.go, docs/data_format_changes/i2927-time-ns-precision.md, internal/db/merge_test.go, tests/integration/index/create_unique_test.go, tests/integration/mutation/create/field_kinds/date_time_test.go, tests/integration/mutation/update/field_kinds/date_time_test.go, tests/integration/query/one_to_many/with_cid_doc_id_test.go, tests/integration/query/simple/with_group_average_filter_test.go, tests/integration/query/simple/with_group_test.go, tests/integration/results.go
Resolves #2927
Add nanosecond precision support to time values.
Was previously only second precision, which is not particularly useful for many applications (such as createdAt timestamps used to allow multiple similar documents to be created within the same second).
=> fix: Add ns precision support to time values

internal/planner/type_join.go, tests/integration/index/query_with_relation_filter_test.go
Resolves #2925
Handles secondary index queries where child found without parent.
Previously the new test would panic further up the callstack (to the prod change), as the parent doc would be nil minus the joined property.
=> fix: Handle index queries where child found without parent

internal/connor/ge.go, internal/connor/gt.go, internal/connor/le.go, internal/connor/lt.go, tests/integration/query/simple/with_filter/with_eq_datetime_test.go, tests/integration/query/simple/with_filter/with_ge_datetime_test.go, tests/integration/query/simple/with_filter/with_gt_datetime_test.go, tests/integration/query/simple/with_filter/with_le_datetime_test.go, tests/integration/query/simple/with_filter/with_lt_datetime_test.go, tests/integration/query/simple/with_filter/with_ne_datetime_test.go
Resolves #2945 
This PR ensure that no error occurs when filtering for a date while having documents with `nil` date value.
added filter integration tests for date
- MacOS
=> fix: Filter with date and document with nil date value

internal/db/fetcher/indexer_iterators.go, internal/planner/multi.go, internal/planner/scan.go, tests/integration/index/query_with_composite_inxed_on_relation_test.go
Resolves #2924
Make multiScanNode keep track of all calls.
The issue was that multiScanNode that keeps track of how many calls to Next() should be made, would call Init() and Start() every time without tracking, which would result in child nodes being initialized and started multiple times, which in turn created index iterators without closing them.
=> fix: Panic with different composite-indexed child objects

.github/workflows/check-tidy.yml, .github/workflows/check-vulnerabilities.yml, Makefile, go.mod, internal/lens/history.go, internal/planner/commit.go, internal/request/graphql/schema/generate.go, tools/cloud/aws/packer/build_aws_ami.pkr.hcl, tools/configs/golangci.yaml, tools/defradb.containerfile
Resolves #2431
- This is a routine version bump of GoLang, the previous bump was done in (https://github.com/sourcenetwork/defradb/pull/2195)
- Also updates the golang version for AWS AMI generation.
- Update all loop todos for 1.22 by removing the copy variables.
=> chore: Bump to GoLang v1.22

cli/start.go, keyring/signer.go, node/acp.go, tests/integration/acp.go
Resolves #2962
I was mostly curious if this will make the vuln checker go green (it doesn't, it just reports it from our internal acp package now), but it is a good change anyway IMO to avoid embedded Go client users from having to directly import the dependency.
=> refactor: Make SourceHub dep internal-only

datastore/badger/v4/datastore.go
Resolves #2964 
Small change that now only sets the badger options `Dir` and `ValueDir` to the  `path`  parameter if the badger option `InMemory` is not `true`.
The crash was happening because badger expects the two Dir values to be nil if InMemory is true.
I chose this fix because it's very simple and requires the least changes. The bulk of the problem is that the `datastore.badger.path` config value gets set to `data` by default regardless of whether  `datastore.store` is set to `memory` and this value gets passed as the `path`  parameter. I didn't think it would be nice to change any of the upstream logic or the signature of the NewDatastore function.
Running standard test suite and using both commands provided in #2964 .
- Debian Linux
=> fix: Ignore badger path if in-memory

go.sum, net/sync_dag.go
Resolves #2930 
This PR removes the use of the ipld traversal function in favor of direct link access. This makes the sync process a bit more efficient and will make it easier to initiate encryption key exchange.
make test
- MacOS
=> chore: Change from ipld traversal to direct link access

docs/website/getting-started.md, docs/website/guides/explain-systems.md, docs/website/guides/schema-relationship.md, docs/website/references/query-specification/database-api.md, docs/website/references/query-specification/mutation-block.md
Resolves #2977 
This PR renames occurrences of _key to _docID when using schemas in the project's markdown documentation.
Github markdown preview
- Debian Linux
=> docs: Rename _key to _docID in docs

http/handler_playground.go, http/server.go, node/node.go
Resolves #2795
This PR adds a log showing the graphql server address. It also updates the API log to show if the playground is enabled.
Manually tested by running `defradb start`
- MacOS
=> fix(i): Log graphql server address

.github/workflows/test-and-upload-coverage.yml
Resolves #3014 
Failed run due to code-cov upload file's name clashing:
https://github.com/sourcenetwork/defradb/actions/runs/10893445627/job/30228379591
Happened in merge commit: [#4989901](https://github.com/sourcenetwork/defradb/commit/49899011a75999543b246d9a852526aa96f60e5c)
Just needed to fix the typo introduced in [`15f244d` (#3000)](https://github.com/sourcenetwork/defradb/pull/3000/commits/15f244d313e33abfa3704cc966560db6cb36276b)
Should be `matrix.view-type` not `matrix.matrix.view-type`, my bad I missed it even while re-reviewing.
=> ci(i): Fix view-type typo to avoid coverage file name clash

internal/request/graphql/schema/collection.go, internal/request/graphql/schema/errors.go, tests/integration/schema/nil_type_test.go
Resolves #3022
Handles missing type in an SDL instead of panicing.
=> fix: Handle missing type in an SDL

README.md, cli/keyring_export.go, cli/keyring_generate.go, cli/keyring_import.go, docs/website/references/cli/defradb_keyring_export.md, docs/website/references/cli/defradb_keyring_generate.md, docs/website/references/cli/defradb_keyring_import.md
Resolves #3033 
The flag and environment variable was kept unchanged from an initial commit in the non-interactive keyring PR. This fixes the mistake.
=> docs(i): Fix incorrect flag and env variable

node/node.go
Resolves #3036
Logs the GQL endpoint correctly on node start.
=> fix: Log GQL endpoint correctly on node start

tests/integration/acp/p2p/create_test.go, tests/integration/acp/p2p/delete_test.go, tests/integration/acp/p2p/update_test.go, tests/integration/test_case.go, tests/integration/utils.go
Resolves #3065 
The main bug was only visible on sourcehub acp using http, due to the identity being copied with the audience value of another node's host failing authentication (the bearer tokens should be unique using correct node's audience). The biggest issue was the way we use `getNodes` and `getNodeCollections`. I would be in favor of completely removing them as they are more troublesome than the utility they provide.
- First commit documents the bug
- Some utility functions were overwriting and producing the wrong node index
- Forbidden bug happening on sourcehub<>http test run: https://github.com/sourcenetwork/defradb/actions/runs/10930293192/job/30342883535?pr=2907
- Resolve import/export documentation and implementation if different (#3067)
- Should likely clean this test utils …
=> fix(i): Sort out invalid testing framework node indexing

internal/db/definition_validation.go, internal/db/schema.go, tests/integration/schema/updates/add/field/with_relation_test.go
Resolves #3074
Correctly handles validation of nearby relation fields in schema patch.
Previously the equality check failed to account for `Kind` being a pointer and thus always flagged relation fields as having mutated.  This was likely introduced in https://github.com/sourcenetwork/defradb/pull/2961 when `Kind` became a pointer.
Collections referenced by relation fields were also not included in the validation set, causing the rules to think that the related object did not exist.
=> fix(i): Validate nearby relation fields in SchemaPatch

client/request/consts.go, client/request/mutation.go, internal/planner/create.go, internal/planner/errors.go, internal/planner/explain.go, internal/planner/mapper/mapper.go, internal/planner/mapper/mutation.go, internal/planner/operations.go, internal/planner/planner.go, internal/planner/upsert.go, internal/request/graphql/parser/mutation.go, internal/request/graphql/schema/descriptions.go, internal/request/graphql/schema/generate.go, tests/integration/explain.go, tests/integration/explain/debug/upsert_test.go, tests/integration/explain/default/upsert_test.go, tests/integration/explain/execute/upsert_test.go, tests/integration/mutation/upsert/simple_test.go
Resolves #783
This PR adds a new upsert GraphQL mutation operation.
- MacOS
=> feat: GraphQL upsert mutation

internal/connor/and.go, internal/connor/or.go, internal/planner/mapper/mapper.go, internal/planner/mapper/targetable.go, internal/request/graphql/schema/generate.go, tests/integration/query/simple/with_null_input_test.go, tests/integration/schema/default_fields.go, tests/integration/schema/filter_test.go
Resolves #3079
This PR fixes an issue where null values within compound filters would panic.
Added integration tests
- MacOS
=> fix(i): Null compound filter panic

.github/workflows/check-vulnerabilities.yml, Makefile
Resolves #3090
- Hacky fix for the vulnerability scanner until they improve the tool (or we solve the vulnerability).
- Make the vulnerability scan fail if new vulnerabilities are introduced and pass if previous known ones remain.
- Tried introducing a vul and it works and ignores the current `x/crisis` one
- Run: https://github.com/sourcenetwork/defradb/actions/runs/11110357130/job/30867868823?pr=3091
=> ci(i): Fix vulnerabilities scan by ignoring x/crises

client/document.go, internal/core/crdt/lwwreg.go, internal/db/collection.go, tests/integration/events.go, tests/integration/mutation/create/field_kinds/one_to_one/with_null_value_test.go, tests/integration/mutation/create/with_null_value_test.go
Resolves #3100
Treat explicitly set nil values like omitted values.
There were a couple of bugs here, I suggest reviewing commit by commit as the old behaviour was documented before being corrected.
=> fix: Treat explicitly set nil values like omitted values

.github/workflows/lint.yml, Makefile, cmd/genopenapi/main.go, http/client_collection.go, http/handler_collection.go, http/handler_store.go, tests/clients/cli/wrapper_collection.go, tools/configs/golangci.yaml
Resolves #3104 
- Bump linter
- Resolve deprecated stuff
- Resolve new linter warning improvements
=> chore(i): Bump linter (`golangci-lint`) to v1.61

docs/data_format_changes/i3137-default-value-fix.md, internal/db/definition_validation.go, internal/db/errors.go, internal/request/graphql/schema/collection.go, internal/request/graphql/schema/errors.go, tests/integration/collection_description/with_default_fields_test.go
Resolves #3133
This PR fixes a bug where default field value types were not properly validated and would cause a panic when creating a new document.
Added an integration test.
- Arch Linux
- Debian Linux
- MacOS
- Windows
=> fix(i): Default field value validation

tests/integration/query/one_to_one/with_fragments_test.go
Resolves #3135 
Adds bug bash tests for gql fragments with inner objects.  No bugs found.
=> test: Add bug bash tests for gql fragments

internal/request/graphql/schema/collection.go, internal/request/graphql/schema/index_parse_test.go, internal/request/graphql/schema/types/types.go, tests/integration/index/array_composite_test.go, tests/integration/index/array_unique_composite_test.go, tests/integration/index/create_composite_test.go, tests/integration/index/create_get_test.go, tests/integration/index/create_unique_composite_test.go, tests/integration/index/query_with_composite_index_field_order_test.go, tests/integration/index/query_with_composite_index_only_filter_test.go, tests/integration/index/query_with_composite_inxed_on_relation_test.go, tests/integration/index/query_with_unique_composite_index_filter_test.go, tests/integration/index/query_with_unique_index_on_relation_filter_test.go, tests/integration/index/update_unique_composite_test.go, tests/integration/mutation/upsert/simple_test.go
Resolves #3132
This PR fixes a mistake I made when refactoring the index directive. The `name` argument of the `includes` fields has been changed to `field`.
Updated unit and integration tests.
- MacOS
=> fix(i): Index directive field arg name

internal/connor/connor.go, internal/connor/eq.go, tests/integration/query/json/with_eq_test.go
Resolves #3141
This PR fixes a bug where the object equality check would panic when comparing with a non object type.
Added integration test.
- MacOS
=> fix(i): Panic in object equal filter

cli/p2p_info.go, cli/purge.go, cli/utils.go, http/errors.go, http/handler.go, http/handler_acp.go, http/handler_ccip.go, http/handler_collection.go, http/handler_extras.go, http/handler_lens.go, http/handler_p2p.go, http/handler_store.go, http/handler_tx.go, http/middleware.go, http/utils.go, tools/configs/golangci.yaml
Resolves #3103 
- Fix the BadRequest in the acp handlers to now be panics
- Make the panics documented under `must` functions
- Add the linter to avoid increasing of undocumented panics
- Ignore linter in existing files outside cli and http (this should either be resolved gradually over time or in a single PR, regardless would prefer to not block this PR because of them)
=> refactor(i): Lint casts & move panics under `must` funcs

.github/workflows/release.yml
Resolves #3169
This PR freezes the goreleaser version to avoid `latest` changes related bugs. At the same time we update the `amd64` build paths to what goreleaser `2.3.2` supports.
tested on my fork
- github CI
=> ci: Freeze goreleaser version and fix amd64 path

cli/p2p_replicator_delete.go, cli/p2p_replicator_set.go, client/mocks/db.go, client/p2p.go, client/replicator.go, docs/website/references/http/openapi.json, http/client_p2p.go, http/handler_p2p.go, http/openapi.go, internal/db/p2p_replicator.go, internal/db/p2p_replicator_test.go, tests/clients/cli/wrapper.go, tests/clients/http/wrapper.go, tests/integration/p2p.go
Resolves #3159
This PR fixes an issue where replicator params that are not modifiable were exposed to the client API.
Existing integration tests.
- MacOS
=> fix(i): SetReplicator and DeleteReplicator params

internal/request/graphql/parser/query.go, tests/integration/query/commits/simple_test.go, tests/integration/query/latest_commits/with_doc_id_test.go, tests/integration/query/simple/with_average_test.go, tests/integration/query/simple/with_count_test.go, tests/integration/query/simple/with_max_test.go, tests/integration/query/simple/with_min_test.go
Resolves #3160
This PR fixes an issue where aliases on top level aggregates would cause a panic.
- MacOS
=> fix(i): Panic on aggregate alias

http/middleware.go, http/server_test.go
Resolves #3177 
This PR adds the Authorization header to the CORS list of allowed headers. This bug what flagged from a partner trying to use authorization from a browser app.
updated unit test with `Access-Control-Request-Headers` header
- MacOS
=> fix: Add Authorization header to CORS allowed headers

tests/integration/query/simple/with_cid_test.go
Resolves #3233
Skip test `TestQuerySimpleWithCid` when detecting changes as the change detector does not support asserting panics.
Note: The CI wont pass until *after* this is merged to develop, so someone will need to change the requiredness of the job so that this can merge.
=> test(i): Skip test when detecting changes

client/request/consts.go, client/request/filter.go, internal/planner/mapper/mapper.go, internal/planner/mapper/targetable.go, internal/request/graphql/parser/errors.go, internal/request/graphql/parser/filter.go, internal/request/graphql/parser/order.go, internal/request/graphql/schema/generate.go, tests/integration/query/one_to_one/with_order_test.go, tests/integration/query/simple/with_order_test.go
Resolves #3196
This PR adds alias targeting to query orderings.
**Aggregate targets are not included in this PR as they require more changes.**
- MacOS
=> feat: Order alias target

tests/integration/acp.go, tests/integration/db.go, tests/integration/events.go, tests/integration/explain.go, tests/integration/lens.go, tests/integration/p2p.go, tests/integration/state.go, tests/integration/utils.go
Resolves #3208
All node-related fields are moved into a separate `nodeState` struct so now we don't need to maintain all slices and node indexes and it's also easier to reason about a node's state.
=> refactor: Consolidate node-related fields into a struct

crypto/aes_test.go
Resolves #3240 
This PR fixes a flaky test where the modification of the cypher text was supposed to cause it to fail decryption. The modification turned out to sometime be the same as the actual cypher text.
Run the `TestDecryptAES` test.
- MacOS
=> fix(i): Remove flakyness of AES decrypt test

internal/db/merge.go, internal/db/merge_test.go, internal/db/messages.go, net/peer.go, net/server.go, tests/integration/acp.go, tests/integration/events.go, tests/integration/query/commits/branchables/peer_index_test.go, tests/integration/query/commits/branchables/peer_test.go, tests/integration/query/commits/branchables/peer_update_test.go, tests/integration/state.go, tests/integration/utils.go
Resolves #3212 
Handles the syncing of collection commits over P2P.
~~Note: The behaviour in `TestQueryCommitsBranchables_HandlesConcurrentUpdatesAcrossPeerConnection` is currently under discussion and may be changed or linked to #3245 and #3246 before this PR is merged.~~ Discussed, and test updated.
=> feat(i): Handle collection commits over P2P

internal/db/fetcher/versioned.go, internal/planner/select.go, internal/request/graphql/schema/descriptions.go, tests/integration/query/simple/with_cid_test.go
Resolves #3214
Adds support for cid-only time travel queries. 
Collection-level commit don't work yet, but I'm going to sort that out in another branch.
Also removes some dead code.
=> feat: Add support for cid-only time travel queries

internal/db/fetcher/versioned.go, internal/planner/select.go, internal/request/graphql/schema/descriptions.go, tests/integration/query/simple/with_cid_branchable_test.go, tests/integration/query/simple/with_cid_doc_id_branchable_test.go, tests/integration/query/simple/with_cid_doc_id_test.go
Resolves #3257
Add support for branchable collection time-traveling.
Also fixes the docID param which was misbehaving (see commit `Create document with actual docID not user provided value`).
Suggest reviewing commit by commit, it should be easier to follow.
Do not review the first commit here - this branch is based of off #3256 - please review that PR first.
=> feat: Add support for branchable collection time-traveling

CONTRIBUTING.md
Resolves #3236
Small PR - adds `https://` to the Discord link to prevent GitHub from interpreting it as an internal repository link.
(*replace*) Describe the tests performed to verify the changes. Provide instructions to reproduce them.
- Arch Linux
- Debian Linux
- MacOS
- Windows
=> docs: Update discord link

acp/README.md, acp/acp_local.go, acp/acp_source_hub.go, cli/acp_relationship_add.go, client/db.go, docs/website/references/cli/defradb_client_acp_relationship_add.md, tests/integration/acp.go, tests/integration/acp/relationship/doc_actor/add/with_target_all_actors_gql_test.go, tests/integration/acp/relationship/doc_actor/add/with_target_all_actors_test.go, tests/integration/acp/relationship/doc_actor/delete/with_target_all_actors_test.go, tests/integration/identity.go, tests/integration/state.go, tests/integration/test_case.go
Resolves #3255 
- Can target all actors using `"*"` to add or delete acp relationships.
- All explicitly added relationships are unaffected upon revocation using `"*"` (they will keep access).
- Commit by commit review should be easier.
- Integration tests
- Manjaro WSL2
=> feat: Add ability to add/delete relationship for all actors

internal/db/base/compare.go, tests/integration/query/one_to_many/with_count_order_test.go, tests/integration/query/one_to_many/with_sum_order_test.go
Resolves #3239
Resolves #2820
This PR enables ordering by aggregated fields by using an alias to target them. This was mostly implemented in a previous PR, so the changes here are tests to verify that it works.
- MacOS
=> feat: Aggregate order alias targeting

acp/README.md, internal/db/permission/check.go, tests/integration/acp/relationship/doc_actor/add/with_manager_gql_test.go, tests/integration/acp/relationship/doc_actor/add/with_manager_test.go, tests/integration/acp/relationship/doc_actor/add/with_only_write_gql_test.go, tests/integration/acp/relationship/doc_actor/add/with_only_write_test.go, tests/integration/acp/relationship/doc_actor/add/with_reader_gql_test.go, tests/integration/acp/relationship/doc_actor/add/with_reader_test.go, tests/integration/acp/relationship/doc_actor/add/with_target_all_actors_gql_test.go, tests/integration/acp/relationship/doc_actor/add/with_target_all_actors_test.go, tests/integration/acp/relationship/doc_actor/add/with_update_gql_test.go, tests/integration/acp/relationship/doc_actor/add/with_update_test.go, tests/integration/acp/relationship/doc_actor/delete/with_target_all_actors_test.go
Resolves #3276 
- Fix the bug where a request without an identity still wouldn't be able to access a document even if there was a "*" relationship
- Added tests
- WSL2 (Manjaro)
=> fix: Make requests with no identity work with "*" target

internal/planner/average.go, internal/planner/count.go, internal/planner/max.go, internal/planner/min.go, internal/planner/sum.go, tests/integration/query/one_to_many/with_average_test.go, tests/integration/query/one_to_many/with_count_test.go, tests/integration/query/one_to_many/with_max_test.go, tests/integration/query/one_to_many/with_min_test.go, tests/integration/query/one_to_many/with_sum_test.go
Resolves #3313
This PR fixes an issue where aggregate filters would only return one result when the first result did not match.
- MacOS
=> fix(i): Aggregate filter returns one result

client/definitions.go, client/document.go, datastore/prefix_query.go, http/client_collection.go, internal/db/description/collection.go, internal/db/fetcher/indexer_iterators.go, internal/db/fetcher/multi.go, internal/db/indexed_docs_test.go, internal/db/view.go, internal/request/graphql/schema/manager.go, node/node.go
Resolves #3334 
In many locations in the code base, we were importing the `"errors"` package in order to utilize the `Join` function. However, we now have this functionality as part of our own errors package. So throughout the codebase import statements, `"errors"` has been changed to `"github.com/sourcenetwork/defradb/errors"`
- Windows
=> chore: Import defradb/errors for Join

acp/acp.go, acp/acp_local.go, acp/acp_local_test.go, acp/acp_source_hub.go, acp/errors.go, acp/source_hub_client.go, node/node.go
Resolves #3358 
***Crude*** implementation to purge the ACP state for LocalACP implementation (SourceHub ACP returns error at the moment). Basically it deletes the entire underlying KVStore and reinitializes it.
Manually, also added unit tests. No current integration purge tests (afaik)
- Arch Linux
- Debian Linux
- MacOS
- Windows
=> feat: Purge ACP state on DB purge

internal/db/collection_index.go, internal/db/fetcher/indexer_iterators.go, internal/db/index.go, tests/integration/schema/updates/add/field/with_index_test.go
Resolves #3365
Completes the fix started in https://github.com/sourcenetwork/defradb/pull/3366 - I missed a test case there and only tested with docs created after the patch.  This adds a new test, testing with docs created before the patch, and then updates all index related references from col.ID to col.RootID.
Sorry about the bother.
=> fix: Maintain indexes across schema versions

internal/db/collection.go
Resolves #3190
Remove compound condition from 1-to-1 validation filter.
At the moment indexes don't work if compound conditions are present. For more details read https://github.com/sourcenetwork/defradb/issues/3299
=> perf: Remove compound condition from 1-1 validation filter

internal/db/collection_acp.go, internal/db/p2p_replicator.go, internal/db/p2p_schema_root.go
Resolves #3386 
This PR resolve the issue where re-adding docs to the p2p tropics on startup resulted in checking doc access. If we know the operation is node specific, meaning it is not to be returned to a client, then we don't need to check access through the ACP engine.
Manual startup test.
- MacOS
=> fix: Ensure no ACP doc check when action is node specific

internal/db/fetcher/wrapper.go
Resolves #3399
This PR fixes an issue where the `Start` function of `wrappingFetcher` would not return an error causing a seg fault when trying to access the fetcher in a subsequent `FetchNext` call.
No added tests. I'm unsure if this is worth testing with mocks, but open to suggestions.
- MacOS
=> fix(i): Fetcher wrapper panic

tests/integration/db.go
Resolves #3402 
In light of this PR:
https://github.com/sourcenetwork/defradb/pull/3400/files
I did a rip grep search:
```
rg -U "if err != nil \{\n.*return nil$"
```
And found one more instance in the code base where non-nill error would still returning `nil`.
=> test(i): Handle error in test setup, don't return nil

go.mod, tools/cloud/aws/packer/build_aws_ami.pkr.hcl, tools/configs/golangci.yaml, tools/defradb.containerfile
Resolves #2912 
- This is a routine version bump of GoLang, the previous bump was done in (https://github.com/sourcenetwork/defradb/pull/2913)
- Also updates the golang version for AWS AMI generation.
=> chore: Bump to GoLang v1.23

cli/start.go
Resolves #3465
Make --no-encryption flag work without keyring
=> fix: Make --no-encryption flag work without keyring

client/request/consts.go, client/request/similarity.go, internal/planner/errors.go, internal/planner/mapper/mapper.go, internal/planner/mapper/similarity.go, internal/planner/operations.go, internal/planner/planner.go, internal/planner/scan.go, internal/planner/select.go, internal/planner/similarity.go, internal/request/graphql/parser/query.go, internal/request/graphql/parser/request.go, internal/request/graphql/schema/generate.go, internal/request/graphql/schema/types/types.go, tests/integration/explain/execute/with_similarity_test.go, tests/integration/query/simple/with_similarity_test.go, tests/integration/schema/default_fields.go, tests/integration/schema/similarity_test.go
Resolves #3349 
This PR adds the possibility to calculate the cosine similarity between a vector field and a given vector.
To achieve this we added the `_similarity` system field which take a target field (part of the parent object) and vector as parameter.
```gql
query {
User{
_similarity(pointsList: {vector: [1, 2, 0]})
}
}
```
Note that the added code to mapper and planner is more of a "bolt on" addition given the current state of that part of the code base. A refactor is expected in the future.
Future work will allow giving a `content` parameter instead of the `vector` if the target field has embedding generation configured. This will enable out-of-the-box RAG queries.
Added cosine similarity to integration testing
- MacOS
=> feat: Add cosine similarity query

docs/data_format_changes/i3477-version-query-consistency.md, internal/planner/commit.go, internal/planner/errors.go, internal/planner/select.go, tests/integration/query/commits/branchables/cid_doc_id_test.go, tests/integration/query/commits/with_cid_test.go, tests/integration/query/commits/with_doc_id_cid_test.go, tests/integration/query/latest_commits/simple_test.go, tests/integration/query/simple/with_cid_doc_id_test.go
Resolves #3476 
Fixes the consistency between regular queries and time-travel queries with respect to the `_version` subquery. Before, the regular queries would return all commits from the start to the current, but time-travel queries only used a "latestCommit" query at the target version, which meant only returning a single commit entry.
This PR implements some semantics changes to the overall commits API, but maintains all necessary backwards compatibility (however, it does introduce new errors when using invalid cid/docid combinations).
New semantics:
- Only doc ID, default max depth, start from "latest" cid
- doc ID + CID, default 0 depth, start from "target" cid
- doc ID + CID + depth, use depth, start from "target" cid
Unchanged semantics:
- doc ID + depth, use depth, start from …
=> fix: Consistent version query semantics

.github/workflows/release.yml
Resolves #3478 
Some change again with the goreleaser target name. This simply fixed the path for the release action cache.
Tested on my fork
=> fix(i): Release cache path

go.mod, tests/integration/encryption/peer_test.go, tests/integration/mutation/create/embeddings/embedding_test.go, tests/integration/mutation/update/embeddings/embedding_test.go, tests/integration/net/simple/peer/with_update_test.go, tests/integration/results.go, tests/integration/test_case.go, tests/integration/utils.go
Resolves https://github.com/sourcenetwork/defradb/issues/3189
Replace the `Validator` interface with `gomega.OmegaMatcher` that doesn't assert directly, but instead matches the actual value against the expected value and returns `bool` as a result. This allows different matchers to be combined.
Moreover, gomega provides a number of very handy matchers that we can use.
=> test: Incorporate gomega matchers

node/store_badger.go
Resolves #3551 
Only give badger a path if not in-memory.
I broke this bringing corekv in.  Keenan fixed this, I'm just doing the typing.
This is tested in https://github.com/sourcenetwork/defradb/pull/3550
=> fix: Only give badger a path if not in-memory

cli/config.go, cli/start.go, cli/test/action/action.go, cli/test/action/collection_describe.go, cli/test/action/schema_add.go, cli/test/action/start.go, cli/test/action/tx_commit.go, cli/test/action/tx_create.go, cli/test/action/txn_action.go, cli/test/integration/schema_add/simple_test.go, cli/test/integration/start/simple_test.go, cli/test/integration/test.go, cli/test/multiplier/multiplier.go, cli/test/multiplier/txn.go, cli/test/state/state.go, docs/website/references/cli/defradb_start.md, go.mod, go.sum
Resolves #3569
Adds the example CLI integration tests using new test framework.
Largely as seen in the demo last week, but with a little more polish.  I think it is good to commit these now and then we can expand them as/when we feel like, and use it as an example for other user-facing stuff (like http).
I have not added the txn-commit multiplier to the CI, as the workflow test files are fairly coupled to executing all tests in the entire repository and I wanted to limit scope here.
=> test: Add example CLI integration tests

tests/integration/index/create_test.go
Resolves #2247
There used to be a panic if multiple `@index` directive with the same index name are defined.
The panic is not there anymore, but the test is good to have.
=> test(i): Add test for same secondary index names

cli/test/action/action.go, cli/test/action/start.go, cli/test/integration/test.go, cli/test/state/state.go
Resolves #3592
Wait for the database to close before progressing to the next test.
Previously the database would close in the background while the next test began, this created a race condition when setting `os.Stderr`.
It was not noticed earlier as I only added a single example test per package - the bug surfaces when there are at least 2.
Credit to Chris, as he suffered with this bug for a while and was a bug help in figuring out where it was. 
I added temporary tests to the package and ran with the `-race` flag.
=> test(i): Wait for database to close before progressing

net/errors.go, net/peer.go
Resolves #3605 
This PR fixes an issue where the PeerInfo sent to DB was sometimes not established before being sent which cased issues on node restart. This is primarily an issue that exists in tests but could also happen on embedded usecases.
make test
- MacOS
=> fix: PeerInfo sync issue

cli/config.go, cli/start.go, docs/website/references/cli/defradb_start.md, internal/db/collection.go, internal/db/collection_delete.go, internal/db/config.go, internal/db/db.go, internal/merkle/clock/clock.go, internal/merkle/clock/errors.go, tests/integration/db.go, tests/integration/signature/commit_test.go, tests/integration/signature/fallback_signer_test.go, tests/integration/signature/verify_test.go, tests/integration/test_case.go
Resolves https://github.com/sourcenetwork/defradb/issues/3607
Allow configuring fallback identity that is used when signing is activated and the identity provided for a request is missing the private key. This happens when requests are sent over HTTP where we do not pass private keys.
Sign deletion blocks (forgot to include it in the previous commits).
=> feat: Configure fallback signer

cli/config.go, cli/start.go, docs/website/references/cli/defradb_start.md, internal/db/collection.go, internal/db/collection_delete.go, internal/db/config.go, internal/db/db.go, internal/merkle/clock/clock.go, internal/merkle/clock/errors.go, tests/integration/db.go, tests/integration/signature/fallback_signer_test.go, tests/integration/test_case.go
Resolves #3628 
The PR revert the inclusion of the fallback signer configuration. There was a bug where if the request did not provide an identity, then the node identity would be used instead of the fallback signer. This was an opaque bug because in its current state, the fallback signer is always the node identity.
At standup we concluded that it would be best to just keep the node identity as the default at all times for now.
make test and manual testing.
- MacOS
=> fix(i): Node identity as default instead of fallback signer

http/handler_collection.go, tests/integration/index/create_get_test.go
Resolves #3642 
This PR fixes a bug where the http handler for `GetIndexes` would call `GetAllIndexes` instead of collection specific indexes.
Note that the first commit documents the bug.
make test
- MacOS
=> fix: Get indexes for a specific collection

client/collection_description.go, client/definitions.go, client/schema_description.go, docs/data_format_changes/i3646-rm-schema-only-cols.md, docs/website/references/http/openapi.json, internal/db/definition_validation.go, internal/planner/mapper/mapper.go, internal/request/graphql/schema/collection.go, internal/request/graphql/schema/generate.go, tests/integration/collection/update/simple/with_filter_test.go, tests/integration/view/one_to_one/simple_test.go
Resolves #3646
Replaces schema-only collections with a boolean `IsEmbeddedOnly` boolean.
I've kept the existing `interface` GQL syntax as-is, we can change that later if we wish, but I'd rather not get into that right now.
=> refactor: Replace schema-only collections with boolean

internal/db/collection_get.go, internal/db/collection_index.go, internal/db/fetcher/fetcher.go, internal/db/fetcher/indexer.go, internal/db/fetcher/indexer_iterators.go, internal/db/fetcher/mocks/fetcher.go, internal/db/fetcher/mocks/utils.go, internal/db/fetcher/versioned.go, internal/db/fetcher/wrapper.go, internal/lens/fetcher.go, internal/planner/order.go, internal/planner/planner.go, internal/planner/scan.go, internal/planner/select.go, internal/planner/type_join.go, tests/integration/explain_result_asserter.go, tests/integration/index/order_query_test.go, tests/integration/index/query_with_composite_index_field_order_test.go
Resolves https://github.com/sourcenetwork/defradb/issues/3650
This change utilizes secondary indexes for order queries, so that not only filtering but, also sorting is optimized.
Whenever a secondary index takes care of ordering on the documents, the planner optimization pass will detect it and ignore `planner.orderNode`.
Tests
- MacOS
=> feat: Utilize secondary indexes for ordering

README.md
=> docs: Update outdated disclaimer about lack of encryption

cli/utils.go, http/middleware.go, internal/db/backup_test.go, internal/db/context.go, internal/db/context_test.go, internal/db/id/collection.go, internal/db/index_test.go, internal/db/merge.go, internal/db/p2p_replicator.go, internal/db/p2p_schema_root.go, internal/db/subscriptions.go, internal/db/txn.go, js/utils.go, tests/integration/lens.go, tests/integration/utils.go
Resolves #3702
Caches collection short ids within txn context, introducing a framework for all future txn-scoped caches to use (such as collection versions, and field short ids).
Performance impact of this PR will be quite small, this will have a much bigger impact when applied to collection versions, and field short-ids.
=> perf: Cache collection short ids within txn context

cli/start.go, cli/test/action/action.go, cli/test/action/start.go, cli/utils.go, http/client.go, http/client_acp.go, http/client_collection.go, http/client_lens.go, http/client_p2p.go, http/client_tx.go, http/handler.go, http/http_client.go, node/message.go, node/node.go, node/node_api.go, tests/integration/events.go, tests/integration/p2p.go
Resolves #3706
This PR introduces a message channels struct to use the cli command context to relay node information outside of the `cli.Start` command. This removes the need to use logs to figure out node state. Some improvement to the synchronousness of the startup process was introduced.
make start
- MacOS
=> chore: Improve node startup sync and feedback

cli/collection_create.go, client/collection.go, client/mocks/collection.go, http/client.go, http/client_collection.go, http/handler_collection.go, internal/db/collection.go, internal/planner/create.go, js/client_collection.go, js/utils.go, tests/clients/cli/wrapper_collection.go, tests/clients/js/wrapper_collection.go, tests/clients/js/wrapper_js.go, tests/integration/utils.go
Resolves [#3754](https://github.com/sourcenetwork/defradb/issues/3754)
Add create doc options to collection create-doc-related methods. 
The options allow specifying parameters for doc encryption.
As opposed to the previous approach with passing the context, this moves parameters handing into the interface and unifies it for all clients.
=> fix: Enable doc encryption for embedded client

cli/index_drop.go, cli/test/action/index_create.go, cli/test/action/index_drop.go, cli/test/action/index_list.go, cli/test/integration/index/create_test.go, cli/test/integration/index/drop_test.go, cli/test/integration/index/list_test.go, docs/website/references/cli/defradb_client_index_drop.md, docs/website/references/http/openapi.json, http/client.go, http/errors.go, http/handler_store.go
Resolves #3770
Make http client check if collection with given name is found when GetCollectionByName called.
Add endpoint for returning all indexes in db.
=> fix: Check if collection exists in index cli commands

docs/data_format_changes/i3788-sec-index-range-queries.md, internal/db/fetcher/indexer.go, internal/db/fetcher/indexer_iterators.go, internal/keys/datastore_index.go, internal/keys/datastore_index_test.go, tests/integration/explain_result_asserter.go, tests/integration/index/array_test.go, tests/integration/index/docs.go, tests/integration/index/json_array_test.go, tests/integration/index/json_composite_test.go, tests/integration/index/json_test.go, tests/integration/index/order_query_test.go, tests/integration/index/query_with_composite_index_field_order_test.go, tests/integration/index/query_with_composite_index_only_filter_test.go, tests/integration/index/query_with_index_combined_filter_test.go, tests/integration/index/query_with_index_on_datetime_test.go, tests/integration/index/query_with_index_only_field_order_test.go, tests/integration/index/query_with_index_only_filter_test.go, tests/integration/index/query_with_unique_composite_index_filter_test.go, tests/integration/index/query_with_unique_index_only_filter_test.go
Resolves #3651
Make secondary indexes use range capabilities of corekv storage.
=> feat: Enable range queries for secondary indexes

cli/start.go, docs/website/references/cli/defradb_start.md
Resolves #3923
Fix the acp config flags on start.
=> fix(i): Fix acp config flags on start

acp/types/types.go, internal/db/store.go, tests/action/add_schema.go, tests/action/identity.go, tests/integration/acp/dac/add_policy/with_no_resources_test.go, tests/integration/acp/dac/p2p/create_test.go, tests/integration/acp/dac/p2p/delete_test.go, tests/integration/acp/dac/p2p/replicator_test.go, tests/integration/acp/dac/p2p/replicator_with_doc_actor_relationship_test.go, tests/integration/acp/dac/p2p/subscribe_test.go, tests/integration/acp/dac/p2p/subscribe_with_doc_actor_relationship_test.go, tests/integration/acp/dac/p2p/update_test.go, tests/integration/acp/nac/relation_admin/schema_add_test.go, tests/integration/acp/nac/schema_add_test.go, tests/integration/acp_dac.go, tests/integration/acp_dac_setup.go, tests/integration/db_setup.go, tests/integration/db_setup_js.go, tests/integration/encryption/peer_acp_test.go, tests/integration/test_case.go, tests/integration/utils.go, tests/state/audience.go, tests/state/audience_js.go, tests/state/state.go
Resolves #3904
- Follow-up to #3758 
- Gate Schema Add Node Operation
- Ensure `admin` behaves properly with new operation.
- Original PR when opened only had this commit: https://github.com/sourcenetwork/defradb/pull/3905/commits/b307e6a1c22c429972176a24883f4ff698078774
- This PR (https://github.com/sourcenetwork/defradb/pull/3918) moved the test action under `tests/action` folder
- So, the first commit handles the refactoring of testing framework to add the missing identity util functions in the `action` package.
Integration tests.
- WSL 2 (Manjaro)
=> feat: Gate schema add op with NAC
