node/node.go

Resolves #1357
Introduces ring-buffer mechanics for WaitForFoo chans.  This means that the go routines modified should never block, and that means that the libp2p `EventBus` should never fill to capacity, meaning it too should never block, which means the main P2P code should never block when doing P2P stuff (e.g. when calling `EventBus.Emit` in `server.PushLog`).
Massive thanks to Fred and John for showing me a very simple way of creating a ring-buffer in Go, I thought it would be way more complicated to do this.

fix: Use ring-buffer for WaitForFoo chans

---

request/graphql/schema/collection.go
request/graphql/schema/errors.go
tests/integration/schema/simple_test.go

Resolves #1191
Improves the NonNull error message when attempting to declare an inline array for an unsupported type.

fix: Improve NonNull error message

---

db/collection.go

Resolves #1268
Documents collection.txn, via use of the Optional type, and code-comment.
A couple of us recently misused this, and these changes should make it harder to do so.

chore: Document collection.txn

---

client/db.go
db/request.go
db/subscriptions.go
db/txn_db.go
request/graphql/parser.go
tests/integration/utils2.go

Resolves #915
Strongly types Request.Errors.
Todo:

feat: Strongly type Request.Errors

---

README.md

Resolves #1418 
This PR is a simply typo fix

fix: Fix typo in readme

---

client/request/consts.go
client/request/select.go
db/collection_update.go
planner/mapper/errors.go
planner/mapper/mapper.go
planner/type_join.go
tests/integration/query/one_to_many/with_group_related_id_alias_test.go
tests/integration/query/one_to_many/with_group_related_id_test.go
tests/integration/query/one_to_many/with_related_id_test.go
tests/integration/query/simple/with_group_test.go
tests/integration/schema/group_test.go

Resolves #1578
Resolves #1551
Part-of: #1279
- Add some tests of existing object_id functionality.
- Add implementation for groupBy alias.
- Add tests for groupBy alias ability.
- Fix the previous panic using alias, with more user friendly error.
- Add tests for panic fix.
- Make a const for `_id`.
- Schema Test to ensure the field we want to alias exists (even though it actually existed from before)
- Commit by commit review should be clean.
- `PR(MAIN):` commit needs the most attention.
- Happy to add more tests if you can think of any cases.
- Happy to remove tests if I introduced any duplicates.
Integration Tests
- Manjaro/Arch WSL2

feat: Add alias to `groupBy` related object

---

.github/dependabot.yml

Resolves #1664
This PR adds a config entry for Dependabot NPM updates.
N/A
- MacOS

fix(i): Add config for Dependabot NPM

---

planner/errors.go
planner/planner.go
planner/type_join.go

Resolves #1711
Returns errors from typeJoinOne instead of ignoring them.
I assume this is a historical accident.

fix: Return errors from typeJoinOne

---

.github/workflows/combine-bot-prs.yml
.github/workflows/push-docker-image-to-registries.yml

Resolves #
- Help combine `dependabot` PRs.
- Can combine based on sub selecters.
Since this is a manual trigger, in order to test this we need to merge this I think.

tools(i): Add a manual triggering workflow to combine PRs

---

tests/integration/query/one_to_one_multiple/simple_test.go

Resolves #1792 
Adds tests for multiple one-one joins.

test(i): Add tests for multiple one-one joins

---

core/clock.go
core/crdt/composite.go
core/crdt/lwwreg.go
core/crdt/lwwreg_test.go
core/replicated.go
db/fetcher/versioned.go
merkle/clock/clock.go
merkle/clock/clock_test.go
merkle/crdt/composite.go
merkle/crdt/lwwreg.go
merkle/crdt/merklecrdt.go
net/dag.go
net/process.go
net/server.go

Resolves #1825
Dont silently ignore potential error in lwwr.  I don't think this error is really possible via normal paths into the codebase, but we should handle it (the root store is publically exposed, and that offers a means to generate this error).
Also trims a few extras from nearby code that I found looking at https://github.com/sourcenetwork/defradb/issues/1038 - I suggest reviewing commit by commit.

fix(i): Dont silently ignore potential error in lwwr

---

tests/change_detector/change_detector_test.go

N/A
This PR fixes an issue where the change detector was not installing dependencies when using a local target branch.
CI
- MacOS

fix(i): Change detector missing deps

---

.github/workflows/test-and-upload-coverage.yml
README.md

Resolves #1921
- Fix workflow badge to the new workflow name
- Fix the omitted pull_request trigger

ci(i): Fix the pull_request trigger and ci badge

---

README.md
db/backup.go
db/fetcher/versioned.go
db/indexed_docs_test.go

Resolves https://github.com/sourcenetwork/defradb/issues/2003
Fixing a few typos

docs(i): Fix typos

---

README.md

N/A
This PR fixes the format of mutations in the readme.
N/A
- MacOS

fix(i): Update mutation in readme

---

tests/integration/view/one_to_many/simple_test.go
tests/integration/view/simple/simple_test.go

Resolves #2218
This works, but was previously untested.

test(i): Add view of view tests

---

db/schema.go

Resolves #2251
Seems like dead code. Not sure if this was the outcome of a partial implementation or just some code that wasn't removed before being merged.

refactor(i): Delete dead code in `db.addSchema` func

---

tests/integration/net/state/simple/peer/with_create_add_field_test.go

Documents #2255
Documents a bug (very likely cache related) when a doc syncs to a node on an older schema version before the schema is updated.

test(i): Document doc sync before schema update bug

---

client/request/aggregate.go
client/request/cid.go
client/request/commit.go
client/request/doc_ids.go
client/request/field.go
client/request/filter.go
client/request/group.go
client/request/limit.go
client/request/mutation.go
client/request/offset.go
client/request/order.go
client/request/select.go
client/request/subscription.go
db/collection_update.go
planner/mapper/mapper.go
planner/planner.go
planner/view.go
request/graphql/parser/commit.go
request/graphql/parser/mutation.go
request/graphql/parser/query.go
request/graphql/parser/request.go
request/graphql/parser/subscription.go

Resolves #2425
Cleans up client/request package, removing some extra stuff, and documenting most of the remaining.
It is not perfect, but it should hopefully be better.

refactor: Clean up client/request package

---

.github/workflows/test-and-upload-coverage.yml

Resolves #2668 
I noticed that someone on the codecov repo mentioned that v4 fixed their issue https://github.com/codecov/codecov-action/issues/598#issuecomment-2063762920. Trying it :)

ci(i): Update codecov to v4

---

internal/db/fetcher/indexer_iterators.go
tests/integration/index/query_with_relation_filter_test.go
tests/integration/index/query_with_unique_index_on_relation_filter_test.go

Resolves #3016
Fix panic with filter on unique composite index on relation.

fix: Panic with filter on unique composite index on relation

---

internal/planner/planner.go
internal/planner/type_join.go
tests/integration/query/one_to_many/one_sided_test.go

Resolves #2830
Adds support for one sided relations.
I thought we had this a while back, but David discovered otherwise.

feat: Add support for one sided relations

---

internal/planner/mapper/mapper.go
tests/integration/query/json/with_aggregate_test.go
tests/integration/query/one_to_many/with_count_filter_test.go

Resolves #3149
This PR fixes an issue with aggregate JSON filtering.
Added integration test.
- MacOS

fix(i): Aggregate json filter

---

internal/connor/all.go
internal/connor/any.go
tests/integration/query/inline_array/with_filter_all_test.go
tests/integration/query/inline_array/with_filter_any_test.go
tests/integration/query/json/with_all_test.go
tests/integration/query/json/with_any_test.go

Resolves #3142
This PR fixes an issue with inline array filters where a non array value would return an error.
Updated / added integration tests.
- MacOS

fix(i): Inline array filter types

---

tests/integration/utils.go

Resolves #3266 
- Remove the overwriting
- Improve logging

ci: Fix the gql mutation running in all tests

---

tests/integration/events.go
tests/integration/utils.go

Resolves #3570
fix some function names in comment
(*replace*) Describe the tests performed to verify the changes. Provide instructions to reproduce them.
- Arch Linux
- Debian Linux
- MacOS
- Windows

chore(i): Fix some function names in comment

---

js/client_collection.go
tests/clients/js/wrapper_collection.go

Resolves #3725
The JS build was broken by the last merged PR, this fixes it.

fix(i): Fix JS build

---

internal/db/data_flow.md

Add new documentation that explains how data flows through DefraDB, from client requests to distributed synchronization across peers.
This documentation serves as a technical reference for developers working with DefraDB, providing clear insights into the system's distributed architecture.

docs: Add data flow documentation

---

Makefile
client/db.go
client/mocks/db.go
event/bus_test.go
event/channel_bus.go
event/channel_bus_test.go
event/event.go
event/event_target_bus.go
event/event_target_bus_test.go
go.mod
go.sum
http/client.go
internal/db/db.go
internal/db/messages.go
internal/db/p2p_replicator_test.go
internal/kms/pubsub.go
net/peer.go
tests/clients/cli/wrapper.go
tests/clients/http/wrapper.go
tests/clients/js/wrapper.go
tests/integration/state.go

Resolves #3793
This PR adds a JavaScript based event system. This is a pre-requisite for the JavaScript p2p system.
Note: Some of the events contain channels and will not be compatible. This will be fixed in a future PR.
Added unit tests.
- MacOS

feat: JavaScript event system
